'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),express=require('express'),http=require('http'),db=require('../db'),S=require('../services/agent_orchestrator/optimization_execution_run');
const originals={},calls=[];for(const k of ['execute','get','list','cancel']){originals[k]=S[k];S[k]=async o=>{calls.push({k,o});return k==='list'?{items:[],next_cursor:null}:{execution_id:o.executionId||'oxr_1',request_id:o.requestId||'oer_1',approved_internal_action:'review_delivery_configuration',execution_mode:'internal_simulation',state:k==='cancel'?'cancelled':'succeeded',version:3,result_code:'internal_review_recorded',provider_contacted:false,provider_mutation_performed:false};};}
delete require.cache[require.resolve('../services/agent_orchestrator/optimization_execution_run_api')];const router=require('../services/agent_orchestrator/optimization_execution_run_api');let server,port;
before(async()=>{const app=express();app.use((req,_res,next)=>{const p=Object.hasOwn(req.headers,'x-principal')?req.headers['x-principal']:'human';req.user={id:7,principalType:p,isOwner:req.headers['x-owner']==='1'};req.session={userId:req.headers['x-session-user']?Number(req.headers['x-session-user']):7};req.sessionID='session-7';req.tenant={id:41};req.tenantRole={permissions:req.headers['x-no-grant']==='1'?[]:[S.PERMISSION]};if(req.headers['x-api-key'])req.viaApiKey=true;next();});app.use('/api/advertising/optimization-execution-runs',router);server=http.createServer(app);await new Promise(r=>server.listen(0,'127.0.0.1',r));port=server.address().port;});
after(async()=>{for(const [k,v] of Object.entries(originals))S[k]=v;await new Promise(r=>server.close(r));});
async function req(path,options={}){const r=await fetch(`http://127.0.0.1:${port}/api/advertising/optimization-execution-runs${path}`,{headers:{'content-type':'application/json',...(options.headers||{})},...options});return {status:r.status,body:await r.json()};}
test('all four genuine HTTP routes use server identity and safe projections',async()=>{let r=await req('/oer_1/execute',{method:'POST',body:JSON.stringify({invocation_id:'invoke-1'})});assert.equal(r.status,200);assert.equal(calls.at(-1).o.tenantId,41);assert.equal(calls.at(-1).o.actorUserId,7);assert.equal(r.body.provider_contacted,false);r=await req('/oxr_1');assert.equal(r.status,200);r=await req('/?limit=10&state=succeeded');assert.equal(r.status,200);r=await req('/oxr_1/cancel',{method:'POST',body:JSON.stringify({expected_version:1})});assert.equal(r.status,200);});
test('strict properties reject tenant actor action and lineage overrides',async()=>{for(const body of [{invocation_id:'x',tenant_id:9},{invocation_id:'x',action:'publish_campaign'},{invocation_id:'x',actor_user_id:9},{invocation_id:'x',provider_id:'x'}])assert.equal((await req('/oer_1/execute',{method:'POST',body:JSON.stringify(body)})).status,400);assert.equal((await req('/oxr_1?credential_ref=x')).status,400);assert.equal((await req('/?unknown=x')).status,400);assert.equal((await req('/oxr_1/cancel',{method:'POST',body:JSON.stringify({expected_version:1,action:'retry'})})).status,400);});
test('session, principal, API-key and permission failures have no owner bypass',async()=>{for(const headers of [{'x-no-grant':'1','x-owner':'1'},{'x-api-key':'1'},{'x-principal':'worker'},{'x-principal':'agent'},{'x-principal':''},{'x-session-user':'8'}]){const denied=await req('/',{headers});assert.ok([401,403].includes(denied.status));}});
test('fail-closed limiter is installed on every route',()=>{const source=require('fs').readFileSync(require.resolve('../services/agent_orchestrator/optimization_execution_run_api'),'utf8');assert.match(source,/failClosed:true/);assert.equal((source.match(/identify,limiter/g)||[]).length,4);});
