'use strict';
const {test,before}=require('node:test'),assert=require('node:assert/strict'),db=require('../db');
const fixture=require('./advertising-meta-delivery-discrepancy-postgres.test');
const S=require('../services/agent_orchestrator/optimization_recommendations'),D=require('../services/agent_orchestrator/delivery_discrepancies');
const permitted=()=>true;
const opts=(f,x={})=>({tenantId:f.tenant,actorUserId:f.user,actorType:'human',principalType:'human',sessionId:`human-${f.tag}`,hasExplicitTenantPermission:permitted,pool:db.getPool(),...x});
const dOpts=(f,x={})=>({...opts(f),principalType:'user',...x});
const snapshot=async(f,table,id)=>{const r=await db.getPool().query(`SELECT row_to_json(x)::text value FROM ${table} x WHERE tenant_id=$1 AND id=$2`,[f.tenant,id]);return r.rows[0]?.value;};
if(!db.hasDb())test('PR8A PostgreSQL requires DATABASE_URL',{skip:'no DATABASE_URL'},()=>{});else{
 before(()=>fixture.bootstrapSchemasOnce());
 test('eligible states create complete frozen lineage, replay exactly, isolate tenants and project safely',async()=>{for(const state of ['verified_active','delivery_pending','discrepancy_detected']){const shared=`shared-${state}-${Date.now()}`,a=await fixture.seedMonitoring(state,`pr8a-a-${state}`,shared),b=await fixture.seedMonitoring(state,`pr8a-b-${state}`,shared),before=await snapshot(a,'orchestrator_campaign_monitoring_runs',a.run);const first=await S.createOrGet(opts(a,{monitoringRunId:a.run,invocationId:'generation-one'})),replay=await S.createOrGet(opts(a,{monitoringRunId:a.run,invocationId:'generation-one'})),other=await S.createOrGet(opts(b,{monitoringRunId:b.run,invocationId:'generation-one'}));assert.deepEqual(replay,first);assert.notEqual(other.recommendation_set_id,first.recommendation_set_id);assert.equal(await snapshot(a,'orchestrator_campaign_monitoring_runs',a.run),before);const row=(await db.getPool().query(`SELECT * FROM orchestrator_campaign_optimization_recommendation_sets WHERE tenant_id=$1 AND id=$2`,[a.tenant,first.recommendation_set_id])).rows[0];for(const [key,value] of [['monitoring_run_id',a.run],['activation_attempt_id',a.attempt],['capability_id',a.cap],['publishing_request_id',a.request],['intent_id',a.intent],['execution_id',a.execution],['reconciliation_run_id',a.recon],['credential_ref_id',a.credential],['ledger_root_hash',a.ledgerRoot]])assert.equal(row[key],value,key);assert(!JSON.stringify(first).includes(a.credential));assert(first.source_classifications.every(x=>S.SAFE_SOURCE_CLASSIFICATIONS.has(x)));}}
 );
 test('pending, observing and failed without a narrow resolved case are ineligible',async()=>{for(const state of ['pending','observing','failed']){const f=await fixture.seedMonitoring(state,`pr8a-ineligible-${state}`);await assert.rejects(S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'no'})),{code:state==='failed'?'resolved_case_required':'source_ineligible'});}});
 test('failed source requires and freezes a narrow resolved PR7D event without mutating source evidence',async()=>{const f=await fixture.seedMonitoring('failed','pr8a-failed-resolved'),monitorBefore=await snapshot(f,'orchestrator_campaign_monitoring_runs',f.run);let c=await D.createOrGet(dOpts(f,{monitoringRunId:f.run}));c=await D.transition(dOpts(f,{caseId:c.discrepancy_case_id,action:'acknowledge',expectedVersion:c.case_version,decisionId:'ack'}));c=await D.transition(dOpts(f,{caseId:c.discrepancy_case_id,action:'resolve',expectedVersion:c.case_version,decisionId:'resolve',classification:'monitoring_failure_accepted',note:'Human accepted the bounded monitoring failure.'}));const caseBefore=await snapshot(f,'orchestrator_campaign_delivery_discrepancy_cases',c.discrepancy_case_id),set=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'resolved'}));assert.equal(set.human_review_outcome,'monitoring_failure_accepted');assert.equal(await snapshot(f,'orchestrator_campaign_monitoring_runs',f.run),monitorBefore);assert.equal(await snapshot(f,'orchestrator_campaign_delivery_discrepancy_cases',c.discrepancy_case_id),caseBefore);});
 test('broad documented resolution cannot independently authorize failed-source analysis',async()=>{const f=await fixture.seedMonitoring('failed','pr8a-broad-resolution');let c=await D.createOrGet(dOpts(f,{monitoringRunId:f.run}));c=await D.transition(dOpts(f,{caseId:c.discrepancy_case_id,action:'acknowledge',expectedVersion:c.case_version,decisionId:'ack'}));c=await D.transition(dOpts(f,{caseId:c.discrepancy_case_id,action:'resolve',expectedVersion:c.case_version,decisionId:'resolve',classification:'other_documented_resolution',note:'Documented but not a positive remediation prerequisite.'}));await assert.rejects(S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'blocked'})),{code:'resolved_case_required'});});
 test('submit, reject, approve, replay, conflicts and approved-successor supersession are transactional',async()=>{const f=await fixture.seedMonitoring('verified_active','pr8a-lifecycle');let rejected=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'reject-generation'}));rejected=await S.transition(opts(f,{setId:rejected.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit-r'}));rejected=await S.transition(opts(f,{setId:rejected.recommendation_set_id,action:'reject',expectedVersion:2,decisionId:'reject-r'}));assert.equal(rejected.state,'rejected');await assert.rejects(S.transition(opts(f,{setId:rejected.recommendation_set_id,action:'submit',expectedVersion:3,decisionId:'reopen'})),{code:'invalid_transition'});
 let first=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'approved-one'}));first=await S.transition(opts(f,{setId:first.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit-1'}));first=await S.transition(opts(f,{setId:first.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve-1'}));const replay=await S.transition(opts(f,{setId:first.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve-1'}));assert.deepEqual(replay,first);await assert.rejects(S.transition(opts(f,{setId:first.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve-1',note:'different'})),{code:'decision_id_conflict'});
 await assert.rejects(db.getPool().query(`UPDATE orchestrator_campaign_optimization_recommendation_sets SET state='superseded',version=version+1,successor_set_id='missing',superseded_at=now() WHERE tenant_id=$1 AND id=$2`,[f.tenant,first.recommendation_set_id]),/foreign key|invalid_approved_successor/);let successor=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'approved-two'}));successor=await S.transition(opts(f,{setId:successor.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit-2'}));successor=await S.transition(opts(f,{setId:successor.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve-2'}));const predecessor=(await db.getPool().query(`SELECT state,successor_set_id,version FROM orchestrator_campaign_optimization_recommendation_sets WHERE tenant_id=$1 AND id=$2`,[f.tenant,first.recommendation_set_id])).rows[0];assert.deepEqual(predecessor,{state:'superseded',successor_set_id:successor.recommendation_set_id,version:4});assert.equal(successor.state,'approved');const active=await db.getPool().query(`SELECT count(*)::int n FROM orchestrator_campaign_optimization_recommendation_sets WHERE tenant_id=$1 AND monitoring_run_id=$2 AND state='approved'`,[f.tenant,f.run]);assert.equal(active.rows[0].n,1);});
 test('separate-connection identical and competing decisions produce one winner and one event',async()=>{const f=await fixture.seedMonitoring('delivery_pending','pr8a-concurrency');let set=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'concurrent'}));set=await S.transition(opts(f,{setId:set.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit'}));const identical=await Promise.all([1,2].map(()=>S.transition(opts(f,{setId:set.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'same'}))));assert.deepEqual(identical[0],identical[1]);const events=await db.getPool().query(`SELECT count(*)::int n FROM orchestrator_campaign_optimization_review_events WHERE tenant_id=$1 AND set_id=$2 AND new_state='approved'`,[f.tenant,set.recommendation_set_id]);assert.equal(events.rows[0].n,1);
 const g=await fixture.seedMonitoring('delivery_pending','pr8a-competing');let other=await S.createOrGet(opts(g,{monitoringRunId:g.run,invocationId:'competing'}));other=await S.transition(opts(g,{setId:other.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit'}));const results=await Promise.allSettled([S.transition(opts(g,{setId:other.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve'})),S.transition(opts(g,{setId:other.recommendation_set_id,action:'reject',expectedVersion:2,decisionId:'reject'}))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);});
 test('event or audit insertion failure rolls the decision and version back',async()=>{const f=await fixture.seedMonitoring('verified_active','pr8a-rollback');let set=await S.createOrGet(opts(f,{monitoringRunId:f.run,invocationId:'rollback'}));set=await S.transition(opts(f,{setId:set.recommendation_set_id,action:'submit',expectedVersion:1,decisionId:'submit'}));const real=db.getPool(),wrapped={connect:async()=>{const c=await real.connect();return {release:()=>c.release(),query:(sql,args)=>/INSERT INTO orchestrator_audit_events/.test(sql)?Promise.reject(Object.assign(new Error('audit failed'),{code:'audit_failed'})):c.query(sql,args)};}};await assert.rejects(S.transition(opts(f,{pool:wrapped,setId:set.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve'})),/audit failed/);const row=(await real.query(`SELECT state,version FROM orchestrator_campaign_optimization_recommendation_sets WHERE tenant_id=$1 AND id=$2`,[f.tenant,set.recommendation_set_id])).rows[0];assert.deepEqual(row,{state:'submitted',version:2});const eventWrapped={connect:async()=>{const c=await real.connect();return {release:()=>c.release(),query:(sql,args)=>/INSERT INTO orchestrator_campaign_optimization_review_events/.test(sql)?Promise.reject(Object.assign(new Error('event failed'),{code:'event_failed'})):c.query(sql,args)};}};await assert.rejects(S.transition(opts(f,{pool:eventWrapped,setId:set.recommendation_set_id,action:'approve',expectedVersion:2,decisionId:'approve-event'})),/event failed/);const after=(await real.query(`SELECT state,version FROM orchestrator_campaign_optimization_recommendation_sets WHERE tenant_id=$1 AND id=$2`,[f.tenant,set.recommendation_set_id])).rows[0];assert.deepEqual(after,{state:'submitted',version:2});});
}
