'use strict';
const {test,before,after,beforeEach,afterEach}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),express=require('express');
const db=require('../db'),service=require('../services/agent_orchestrator/optimization_recommendations'),router=require('../services/agent_orchestrator/optimization_recommendations_api');
const originals=Object.fromEntries(['createOrGet','get','list','transition'].map(k=>[k,service[k]])),originalPool=db.getPool;
let server,port,calls;
const safeSet=(x={})=>({recommendation_set_id:'set-1',source_monitoring_run_reference:'run-1',state:'draft',version:1,recommendations:[],source_classifications:[],source_failure_classifications:[],human_review_outcome:null,created_at:'2026-01-01T00:00:00Z',submitted_at:null,approved_at:null,rejected_at:null,superseded_at:null,audit_reference:'audit',...x});
before(async()=>{const app=express();app.use((req,_res,next)=>{const kind=req.headers['x-omit-principal']==='1'?undefined:(Object.hasOwn(req.headers,'x-principal')?req.headers['x-principal']:'human');req.user={id:7,principalType:kind,isOwner:req.headers['x-owner']==='1'};req.session={userId:req.headers['x-session-user']?Number(req.headers['x-session-user']):7};req.sessionID='session-7';req.tenant={id:41};req.tenantRole={permissions:req.headers['x-no-grant']==='1'?[]:[service.PERMISSION]};if(req.headers['x-api-key']==='request')req.viaApiKey=true;if(req.headers['x-api-key']==='user')req.user.viaApiKey=true;next();});app.use('/api/agent-orchestrator/optimization-recommendations',router);server=http.createServer(app);await new Promise(r=>server.listen(0,'127.0.0.1',r));port=server.address().port;});
after(async()=>{for(const[k,v]of Object.entries(originals))service[k]=v;db.getPool=originalPool;await new Promise(r=>server.close(r));});
beforeEach(()=>{calls=[];router._limiter.reset();db.getPool=()=>({marker:'pool'});service.createOrGet=async o=>(calls.push(['create',o]),safeSet());service.get=async o=>(calls.push(['get',o]),safeSet());service.list=async o=>(calls.push(['list',o]),{items:[safeSet()],next_cursor:null});service.transition=async o=>{calls.push([o.action,o]);if(o.decisionId==='collision')throw Object.assign(new Error(),{code:'decision_id_conflict'});if(o.expectedVersion===99)throw Object.assign(new Error(),{code:'version_conflict'});return safeSet({state:{submit:'submitted',approve:'approved',reject:'rejected'}[o.action],version:2});};});
afterEach(()=>{for(const[k,v]of Object.entries(originals))service[k]=v;db.getPool=originalPool;});
function request(method,path,body,headers={}){return new Promise((resolve,reject)=>{const payload=body===undefined?null:JSON.stringify(body),req=http.request({hostname:'127.0.0.1',port,method,path,headers:{...headers,...(payload?{'content-type':'application/json','content-length':Buffer.byteLength(payload)}:{})}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw||'{}')}));});req.on('error',reject);if(payload)req.write(payload);req.end();});}
const base='/api/agent-orchestrator/optimization-recommendations';
test('all six HTTP routes derive tenant, actor, session and exact grant from context',async()=>{const specs=[['POST','/',{monitoring_run_id:'run-1',invocation_id:'generation-1'},'create'],['GET','/set-1',undefined,'get'],['GET','/?limit=20&cursor=0&state=draft',undefined,'list'],['POST','/set-1/submit',{expected_version:1,decision_id:'submit-1'},'submit'],['POST','/set-1/approve',{expected_version:1,decision_id:'approve-1'},'approve'],['POST','/set-1/reject',{expected_version:1,decision_id:'reject-1'},'reject']];for(const[m,p,b,a]of specs){const r=await request(m,base+p,b);assert.equal(r.status,200,`${m} ${p}`);const call=calls.at(-1);assert.equal(call[0],a);assert.equal(call[1].tenantId,41);assert.equal(call[1].actorUserId,7);assert.equal(call[1].principalType,'human');assert.equal(call[1].hasExplicitTenantPermission(service.PERMISSION),true);}});
test('principal type is explicit and every absent or non-human type fails before service',async()=>{for(const kind of [null,'','unknown','api_key','service','service_account','worker','automation','autonomous','agent','user']){const headers=kind===null?{'x-omit-principal':'1'}:{'x-principal':kind};const r=await request('GET',base+'/',undefined,headers);assert.equal(r.status,401,String(kind));}for(const flag of ['request','user']){const r=await request('GET',base+'/',undefined,{'x-api-key':flag});assert.equal(r.status,401);}assert.equal(calls.length,0);});
test('session and tenant grant fail closed without owner or platform bypass',async()=>{let r=await request('GET',base+'/',undefined,{'x-session-user':'8'});assert.equal(r.status,401);for(const kind of ['human','platform_owner','platform_admin']){r=await request('GET',base+'/',undefined,{'x-principal':kind,'x-owner':'1','x-no-grant':'1'});assert.equal(r.status,kind==='human'?403:401);}assert.equal(calls.length,0);});
test('unknown and identity override properties and query fields are rejected',async()=>{for(const body of [{monitoring_run_id:'run',invocation_id:'i',tenant_id:9},{monitoring_run_id:'run',invocation_id:'i',actor_id:9},{monitoring_run_id:'run',invocation_id:'i',session_id:'x'},{monitoring_run_id:'run',invocation_id:'i',unknown:true}]){const r=await request('POST',base+'/',body);assert.equal(r.status,400);}let r=await request('POST',base+'/set/submit',{expected_version:1,decision_id:'d',permission:'x'});assert.equal(r.status,400);r=await request('GET',base+'/?order=state');assert.equal(r.status,400);assert.equal(calls.length,0);});
test('bounded list inputs, replay surface, decision collision and version conflict are HTTP-visible',async()=>{let r=await request('GET',base+'/?limit=50&cursor=10&state=submitted');assert.equal(r.status,200);assert.deepEqual({limit:calls[0][1].limit,cursor:calls[0][1].cursor,state:calls[0][1].state},{limit:'50',cursor:'10',state:'submitted'});r=await request('POST',base+'/set/approve',{expected_version:1,decision_id:'same'});assert.equal(r.status,200);r=await request('POST',base+'/set/approve',{expected_version:1,decision_id:'same'});assert.equal(r.status,200);r=await request('POST',base+'/set/approve',{expected_version:1,decision_id:'collision'});assert.equal(r.status,409);r=await request('POST',base+'/set/approve',{expected_version:99,decision_id:'new'});assert.equal(r.status,409);});
test('the same fail-closed limiter is installed on all six routes',()=>{const routes=router.stack.filter(x=>x.route).map(x=>x.route);assert.equal(routes.length,6);for(const route of routes)assert(route.stack.some(x=>x.handle===router._limiter));});
