'use strict';
const {test,before,after,beforeEach,afterEach}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),express=require('express');
const db=require('../db'),service=require('../services/agent_orchestrator/optimization_execution'),router=require('../services/agent_orchestrator/optimization_execution_api');
const originals=Object.fromEntries(['createOrGet','get','list','transition'].map(k=>[k,service[k]])),originalPool=db.getPool;
let server,port,calls;
const safe=(x={})=>({request_id:'request-1',recommendation_set_id:'set-1',recommendation_id:'rec-1',proposed_internal_action:'review_campaign_configuration',rationale:'Review internal configuration',safe_evidence_references:['monitoring evidence'],state:'draft',version:1,authorized_creator_user_id:7,deciding_user_id:null,created_at:'2026-01-01T00:00:00Z',submitted_at:null,decided_at:null,execution_performed:false,provider_contacted:false,...x});
before(async()=>{const app=express();app.use((req,_res,next)=>{const kind=req.headers['x-omit-principal']==='1'?undefined:(Object.hasOwn(req.headers,'x-principal')?req.headers['x-principal']:'human');req.user={id:7,principalType:kind,isOwner:req.headers['x-owner']==='1'};req.session={userId:req.headers['x-session-user']?Number(req.headers['x-session-user']):7};req.sessionID='session-7';req.tenant={id:41};req.tenantRole={permissions:req.headers['x-no-grant']==='1'?[]:[service.PERMISSION]};if(req.headers['x-api-key'])req.viaApiKey=true;next();});app.use('/api/advertising/optimization-executions',router);server=http.createServer(app);await new Promise(r=>server.listen(0,'127.0.0.1',r));port=server.address().port;});
after(async()=>{for(const[k,v]of Object.entries(originals))service[k]=v;db.getPool=originalPool;await new Promise(r=>server.close(r));});
beforeEach(()=>{calls=[];router._limiter.reset();db.getPool=()=>({marker:'pool'});service.createOrGet=async o=>(calls.push(['create',o]),safe());service.get=async o=>(calls.push(['get',o]),safe());service.list=async o=>(calls.push(['list',o]),{items:[safe()],next_cursor:'opaque'});service.transition=async o=>{calls.push([o.action,o]);if(o.decisionId==='collision')throw Object.assign(new Error(),{code:'decision_id_conflict'});if(o.expectedVersion===99)throw Object.assign(new Error(),{code:'version_conflict'});return safe({state:{submit:'submitted',approve:'approved',reject:'rejected'}[o.action],version:2});};});
afterEach(()=>{for(const[k,v]of Object.entries(originals))service[k]=v;db.getPool=originalPool;});
function request(method,path,body,headers={}){return new Promise((resolve,reject)=>{const payload=body===undefined?null:JSON.stringify(body),req=http.request({hostname:'127.0.0.1',port,method,path,headers:{...headers,...(payload?{'content-type':'application/json','content-length':Buffer.byteLength(payload)}:{})}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw||'{}')}));});req.on('error',reject);if(payload)req.write(payload);req.end();});}
const base='/api/advertising/optimization-executions';
test('all six HTTP routes derive tenant and human identity from context',async()=>{const specs=[['POST','/',{recommendation_set_id:'set-1',recommendation_id:'rec-1',invocation_id:'create-1'},'create'],['GET','/request-1',undefined,'get'],['GET','/?limit=20&cursor=0&state=draft',undefined,'list'],['POST','/request-1/submit',{expected_version:1,decision_id:'submit-1'},'submit'],['POST','/request-1/approve',{expected_version:1,decision_id:'approve-1'},'approve'],['POST','/request-1/reject',{expected_version:1,decision_id:'reject-1'},'reject']];for(const[m,p,b,a]of specs){const r=await request(m,base+p,b);assert.equal(r.status,200,`${m} ${p}`);assert.equal(calls.at(-1)[0],a);assert.equal(calls.at(-1)[1].tenantId,41);assert.equal(calls.at(-1)[1].actorUserId,7);assert.equal(calls.at(-1)[1].hasExplicitTenantPermission(service.PERMISSION),true);assert.equal(r.body.execution_performed??r.body.items?.[0].execution_performed,false);assert.equal(r.body.provider_contacted??r.body.items?.[0].provider_contacted,false);}});
test('principal, session and exact tenant grant fail closed without role bypass',async()=>{for(const kind of [null,'','unknown','user','api_key','service','service_account','worker','automation','autonomous','agent']){const h=kind===null?{'x-omit-principal':'1'}:{'x-principal':kind};assert.equal((await request('GET',base+'/',undefined,h)).status,401);}assert.equal((await request('GET',base+'/',undefined,{'x-api-key':'1'})).status,401);assert.equal((await request('GET',base+'/',undefined,{'x-session-user':'8'})).status,401);assert.equal((await request('GET',base+'/',undefined,{'x-owner':'1','x-no-grant':'1'})).status,403);assert.equal(calls.length,0);});
test('identity overrides, unknown properties and unsafe query fields are rejected',async()=>{for(const extra of [{tenant_id:9},{actor_user_id:9},{principalType:'human'},{unknown:true}])assert.equal((await request('POST',base+'/',{recommendation_set_id:'s',recommendation_id:'r',invocation_id:'i',...extra})).status,400);assert.equal((await request('POST',base+'/request-1/submit',{expected_version:1,decision_id:'d',permission:'x'})).status,400);assert.equal((await request('GET',base+'/?order=state')).status,400);assert.equal(calls.length,0);});
test('pagination, filtering, replay and collision errors remain safely exposed',async()=>{let r=await request('GET',base+'/?limit=50&cursor=10&state=submitted');assert.equal(r.status,200);assert.deepEqual({limit:calls[0][1].limit,cursor:calls[0][1].cursor,state:calls[0][1].state},{limit:'50',cursor:'10',state:'submitted'});for(let i=0;i<2;i++)assert.equal((await request('POST',base+'/request-1/approve',{expected_version:1,decision_id:'same'})).status,200);assert.equal((await request('POST',base+'/request-1/approve',{expected_version:1,decision_id:'collision'})).status,409);assert.equal((await request('POST',base+'/request-1/approve',{expected_version:99,decision_id:'new'})).status,409);});
test('the fail-closed limiter is installed on every route',()=>{const routes=router.stack.filter(x=>x.route).map(x=>x.route);assert.equal(routes.length,6);for(const route of routes)assert(route.stack.some(x=>x.handle===router._limiter));});
