uploads = []
generated = []

[[outputs]]
id = "Vy3Sem690SIpbg8VvFm3F"
uri = "file://infogenie-backup.tar.gz"
type = "unspecified"
title = "InfoGenie — Source Code Backup (latest)"

[[outputs]]
id = "cV4y0z-pEjKFlrPOaoa_t"
uri = "file://infogenie-full-code.txt"
type = "text"
title = "InfoGenie — Complete Source Code"
