/* eslint-disable */
// Shared feature catalogue used by both build_user_manual.js and capture_screenshots.js.
// Every navigable view in the InfoGenie SPA appears here exactly once.

const C = {
  navy: '#0A1628', teal: '#16C5C8', blue: '#3B82F6', purple: '#8B5CF6',
  green: '#10B981', amber: '#F59E0B', red: '#EF4444',
};

const SECTIONS = [
  {
    nav: 'Getting Started',
    icon: '🏁',
    color: C.navy,
    summary: 'The home screen — where every InfoGenie session begins.',
    features: [
      { id: 'home', name: 'Home / Welcome Screen', icon: '🏠', shot: 'home.jpg',
        what: 'The starting point of the platform. Enter your website (or pick an industry), choose a target country, and trigger the full intelligence run from a single button.',
        inputs: ['Website URL or industry/sector dropdown', 'Target country', '"Analyse Now" trigger'],
        outputs: ['Triggers the full analysis pipeline (competitors, KPIs, Battle Plan, audiences)', 'Routes you straight to the Intelligence Report dashboard'],
        how: 'Open the app — you land here automatically. Type your domain (or pick a sector if you don\'t have one yet), confirm the country, then click "Analyse Now". Within ~60 seconds the rest of the platform is populated with live data.' },
      { id: 'roadmap', name: 'Get Started Roadmap', icon: '🗺️', shot: 'roadmap.jpg',
        what: 'A guided checklist that walks you through every first-time setup step in priority order.',
        inputs: ['Click any open task to jump straight to that module'],
        outputs: ['Live progress bar', 'Task completion ticks across the platform'],
        how: 'Open Roadmap any time you feel stuck. Knock off the next open task — each one unlocks more downstream value.' },
    ],
  },
  {
    nav: 'Analyse',
    icon: '🔍',
    color: C.teal,
    summary: 'Understand the market through competitor intelligence, search data, and live monitoring.',
    features: [
      { id: 'dashboard', name: 'Intelligence Report (Dashboard)', icon: '📊', shot: 'dashboard.jpg',
        what: 'High-level overview of the competitive landscape with AI-driven growth recommendations.',
        inputs: ['Website URL or industry/sector', 'Target country'],
        outputs: ['KPI grid (CTR, ROAS, traffic)', 'Side-by-side performance charts', '12-month traffic & spend trends', 'Competitor intelligence summary'],
        how: 'Enter your website or pick an industry on the home screen, choose your target country, and click "Analyse Now". The dashboard populates within 60 seconds.' },
      { id: 'competitors', name: 'Competitive Intelligence Engine', icon: '⚔️', shot: 'competitors.jpg',
        what: 'Deep-dive analysis into specific competitors — traffic sources, threat levels, ad creative, and counter-attack plans.',
        inputs: ['Manual competitor URLs (optional)'],
        outputs: ['Competitor cards', 'Threat-level scoring', 'Ad creative insights', '"Attack Plan" per competitor'],
        how: 'Open the Competitors view after running an analysis. Click any competitor card to drill into their channel mix and see the recommended counter-strategy.' },
      { id: 'intelligence', name: 'Intelligence Hub', icon: '📡', shot: 'intelligence.jpg',
        what: 'Real-time monitoring of competitor signals and predictive market moves.',
        inputs: ['Auto-derived from analysis'],
        outputs: ['Predictive signals', 'Budget-shift alerts', '90-day domination roadmap', 'Exportable report'],
        how: 'Open the Intelligence Hub from the Analyse menu. Use "Counter This Message" on any competitor message to launch a counter-campaign in one click.' },
      { id: 'battleplan', name: 'AI Battle Plan', icon: '🛡️', shot: 'battleplan.jpg',
        what: 'Strategic execution roadmap tailored to the identified market gaps.',
        inputs: ['Competitor analysis results'],
        outputs: ['Implementation steps', '90-day strategic priorities', 'Tactical playbook'],
        how: 'Generated automatically after an analysis run. Review priorities top-to-bottom and assign owners.' },
      { id: 'battle-cards', name: 'Competitor Battle Cards', icon: '🪪', shot: 'battle-cards.jpg',
        what: 'Auto-generated 1-page intel briefs per competitor — positioning, strengths, weaknesses, and how to win against them.',
        inputs: ['Competitor name + domain (or pick from analysed list via dropdown)'],
        outputs: ['Side-by-side battle card', 'Win/loss themes', 'Exportable PDF'],
        how: 'Click "Generate Battle Card", pick a competitor from the dropdown (or type one), and download the resulting one-pager for your sales team.' },
      { id: 'ad-library', name: 'Ad Library Spy', icon: '🕵️', shot: 'ad-library.jpg',
        what: 'Pulls competitors\' currently-running ads from Meta, Google, LinkedIn, TikTok and X — all in one fan-out.',
        inputs: ['Brand name', 'Country', 'Platform checklist (Meta / Google / LinkedIn / TikTok / X)'],
        outputs: ['Per-platform ad list with creative, copy and platform link'],
        how: 'Type the brand, pick the country from the search-able dropdown, tick the platforms you want, then hit Run. Each platform fetches in parallel.' },
      { id: 'tech-stack', name: 'Competitor Tech Stack Detector', icon: '🧱', shot: 'tech-stack.jpg',
        what: 'Identifies the analytics, ad platforms, CMS, and frameworks any competitor is running.',
        inputs: ['Up to 5 competitor domains (or click "Use my analysed competitors" to auto-fill)'],
        outputs: ['Side-by-side tech matrix', 'Differences vs your stack'],
        how: 'Paste the domains (or click the AI-suggest button), then hit Detect. Differences highlight gaps you should investigate.' },
      { id: 'pricing-watch', name: 'Competitor Pricing Watcher', icon: '💰', shot: 'pricing-watch.jpg',
        what: 'Tracks competitor product URLs to extract and monitor pricing changes over time.',
        inputs: ['Label, competitor name, product URL (or pick a competitor from the dropdown to auto-fill all 3)'],
        outputs: ['Latest scraped price', 'Price-history chart per target'],
        how: 'Add a target, then re-scan manually or wait for the cron job. Each target shows price-change deltas.' },
      { id: 'job-board-spy', name: 'Job Board Spy', icon: '💼', shot: 'job-board-spy.jpg',
        what: 'Monitors competitor hiring patterns to infer where they are investing strategic growth.',
        inputs: ['Competitor company names'],
        outputs: ['Open-role list', 'Department breakdown', 'Hiring-velocity signal'],
        how: 'Add competitor names — InfoGenie searches public job boards and surfaces what each is hiring for.' },
      { id: 'sov-tracker', name: 'Share of Voice Tracker', icon: '📈', shot: 'sov-tracker.jpg',
        what: 'Time-series share of media mentions across you and your competitors.',
        inputs: ['Brand list (auto-derived from analysis)'],
        outputs: ['Stacked SoV chart', 'Trend deltas'],
        how: 'Open the tracker — it auto-runs daily and surfaces who is gaining or losing voice.' },
      { id: 'crisis-radar', name: 'Crisis Radar', icon: '🚨', shot: 'crisis-radar.jpg',
        what: 'Daily anomaly detection on mention volume and sentiment to detect brand risks early.',
        inputs: ['Auto-monitored brands'],
        outputs: ['Anomaly alerts (Slack + email if configured)', 'Severity scoring'],
        how: 'Configure thresholds once, then leave it running. Crisis Radar pings you the moment volume or sentiment breaks pattern.' },
      { id: 'icp-studio', name: 'ICP Studio', icon: '🎯', shot: 'icp-studio.jpg',
        what: 'Builds detailed Ideal Customer Profiles using voice-of-customer signals.',
        inputs: ['Brand intelligence data', 'Optional manual prompts'],
        outputs: ['Persona profiles (demographics, pains, motivations)', 'Tile-level activations: ads, social, email'],
        how: 'Click any ICP tile to activate that channel. Use "Save ICP" to lock in the persona for future runs.' },
      { id: 'voc', name: 'Voice of Customer Mining', icon: '🗣️', shot: 'voc.jpg',
        what: 'AI clusters recent mentions into themes — top complaints, top praises, feature requests, and unmet needs.',
        inputs: ['Brand name (auto-pulled from analysis)'],
        outputs: ['Theme clusters with example quotes', 'Sentiment per theme'],
        how: 'Open VoC and let it run — it pulls a fresh sweep of mentions and rebuilds the themes each time.' },
      { id: 'review-aggregator', name: 'Review Aggregator', icon: '⭐', shot: 'review-aggregator.jpg',
        what: 'Pulls recent reviews from Trustpilot, G2, Google and other platforms into one analysis surface.',
        inputs: ['Brand name + sources'],
        outputs: ['Unified review feed', 'Average rating', 'Theme breakdown'],
        how: 'Add the brand, choose the sources, hit Aggregate.' },
      { id: 'glassdoor', name: 'Glassdoor Sentiment', icon: '🏢', shot: 'glassdoor.jpg',
        what: 'Analyses competitor employee reviews to infer internal health, churn risk and culture problems.',
        inputs: ['Competitor company names'],
        outputs: ['Employee sentiment score', 'Top complaint themes'],
        how: 'Add a competitor — InfoGenie pulls public Glassdoor reviews and clusters the themes.' },
      { id: 'mentions', name: 'Mention Tracker', icon: '📰', shot: 'mentions.jpg',
        what: 'Tracks brand and competitor mentions across news and the open web.',
        inputs: ['Brand & competitor list'],
        outputs: ['Live mention feed', 'Sentiment-tagged'],
        how: 'Open Mentions and use the search box to filter by source, sentiment or date.' },
      { id: 'reddit', name: 'Reddit Intel', icon: '🔴', shot: 'reddit.jpg',
        what: 'Deep dive into subreddit discussions for market research, sentiment and reply opportunities.',
        inputs: ['Brand or query string', 'Scan Now trigger'],
        outputs: ['Subreddit mentions with sentiment', 'AI-suggested replies in your brand voice'],
        how: 'Click "Scan now" and wait ~10 seconds. Use the Reply Studio tab to draft on-brand responses.' },
      { id: 'reddit-pulse', name: 'Reddit & Community Pulse', icon: '👽', shot: 'reddit-pulse.jpg',
        what: 'Searches subreddits for brand mentions from the last 7 days with AI sentiment classification.',
        inputs: ['Brand name'],
        outputs: ['7-day mention chart', 'Top threads with reply hooks'],
        how: 'Open Reddit Pulse — the 7-day window auto-refreshes when you click Scan.' },
      { id: 'twitter-pulse', name: 'Twitter / X Pulse', icon: '🐦', shot: 'twitter-pulse.jpg',
        what: 'Real-time monitoring of brand conversations and trending topics on X.',
        inputs: ['Brand handle or hashtag'],
        outputs: ['Tweet stream', 'Sentiment + engagement scores'],
        how: 'Type the handle and hit Search — results update live.' },
      { id: 'quora-mining', name: 'Quora Mining', icon: '❓', shot: 'quora-mining.jpg',
        what: 'Extracts insights from Quora questions and answers in your category.',
        inputs: ['Topic or brand query'],
        outputs: ['Top questions', 'Answer-gap opportunities'],
        how: 'Search a topic and use the surfaced questions as content briefs.' },
      { id: 'youtube-monitor', name: 'YouTube Channel Monitor', icon: '▶️', shot: 'youtube-monitor.jpg',
        what: 'Tracks competitor uploads, view velocity and comment sentiment via live YouTube search.',
        inputs: ['Competitor channel names'],
        outputs: ['Recent uploads with view counts', 'Comment-sentiment summary'],
        how: 'Add channels — InfoGenie polls them and surfaces what is breaking out.' },
      { id: 'podcast-monitor', name: 'Podcast Mention Monitor', icon: '🎙️', shot: 'podcast-monitor.jpg',
        what: 'Finds podcast episodes that mention your brand using live search.',
        inputs: ['Brand name'],
        outputs: ['Episode list with show, host and timestamp'],
        how: 'Run a scan — each result links straight to the episode.' },
      { id: 'newsletter-tracker', name: 'Newsletter Tracker', icon: '📧', shot: 'newsletter-tracker.jpg',
        what: 'Monitors competitor newsletter archives to extract subject lines, cadence and angles.',
        inputs: ['Competitor newsletter URL or name'],
        outputs: ['Subject-line list', 'Send-frequency chart'],
        how: 'Add a competitor newsletter — InfoGenie indexes their public archive.' },
      { id: 'trending-topics', name: 'Trending Topics', icon: '🔥', shot: 'trending-topics.jpg',
        what: 'Identifies what is currently spiking in your category via live web search.',
        inputs: ['Industry or category'],
        outputs: ['Ranked trending topic list', 'Velocity scores'],
        how: 'Pick the category — refreshed every few hours.' },
      { id: 'content-gaps', name: 'Content Gaps', icon: '🧩', shot: 'content-gaps.jpg',
        what: 'Identifies topics and keywords competitors are ranking for but you are not.',
        inputs: ['Your domain + competitor domains'],
        outputs: ['Gap keyword list', 'Suggested article briefs'],
        how: 'Run the gap analysis — each result includes a brief you can hand to AI Content.' },
      { id: 'intent-map', name: 'Search Intent Map', icon: '🧭', shot: 'intent-map.jpg',
        what: 'Classifies keywords by user intent (Informational / Transactional / Commercial / Navigational).',
        inputs: ['Generate Intent Map trigger'],
        outputs: ['Keyword → intent mapping', 'Landing-page-type recommendations'],
        how: 'Click "Generate" and use the resulting clusters to plan content type per topic.' },
      { id: 'keyword-map', name: 'Keyword–Page Map', icon: '🗺️', shot: 'keyword-map.jpg',
        what: 'Maps primary and supporting keywords to specific pages to avoid SEO cannibalisation.',
        inputs: ['Generate Map trigger'],
        outputs: ['Visual site architecture', 'Keyword → URL assignments'],
        how: 'Click "Generate Map" — InfoGenie scans your site and assigns each keyword cluster to the best-fit page.' },
      { id: 'keyword-explorer', name: 'Keyword Explorer', icon: '🔬', shot: 'keyword-explorer.jpg',
        what: 'Detailed research tool for discovering new keyword opportunities with volume and difficulty metrics.',
        inputs: ['Seed keyword + country'],
        outputs: ['Long-tail variants with metrics'],
        how: 'Type a seed and let the explorer fan out related queries.' },
      { id: 'serp', name: 'Google Search Intelligence', icon: '🔎', shot: 'serp.jpg',
        what: 'Live Google SERP tracker for any query, country and result type.',
        inputs: ['Search query', 'Country', 'Type (Organic / News)'],
        outputs: ['Live ranking positions', 'Competitor ad presence', 'Organic visibility'],
        how: 'Type a query, choose a country, choose Organic or News, and hit Search.' },
      { id: 'serp-tracker', name: 'SERP Position Tracker', icon: '📍', shot: 'serp-tracker.jpg',
        what: 'Tracks your domain\'s Google rank for target keywords across countries — over time.',
        inputs: ['Keyword list + country + your domain'],
        outputs: ['Daily rank chart', 'Movement alerts'],
        how: 'Add the keywords once; the tracker polls daily.' },
      { id: 'backlinks', name: 'Backlink Intel', icon: '🔗', shot: 'backlinks.jpg',
        what: 'Total backlinks and referring-domain data for any domain.',
        inputs: ['Target domain'],
        outputs: ['Referring-domain list', 'Authority scores'],
        how: 'Type a domain — useful for sizing competitor link profiles.' },
      { id: 'backlink-monitor', name: 'Backlink Monitor', icon: '🛰️', shot: 'backlink-monitor.jpg',
        what: 'Continuous monitoring of backlink-profile changes and new link discoveries.',
        inputs: ['Your domain'],
        outputs: ['New / lost link feed', 'Change deltas'],
        how: 'Set the watched domain once — alerts when links are gained or lost.' },
    ],
  },
  {
    nav: 'Create',
    icon: '✏️',
    color: C.blue,
    summary: 'Build and manage every marketing asset — copy, creative, video, scripts, calendars.',
    features: [
      { id: 'brand-assets', name: 'Brand Creative Library', icon: '🖼️', shot: 'brand-assets.jpg',
        what: 'Centralised repository for all brand-related files (logos, banners, social, video, PDFs).',
        inputs: ['File uploads up to 50MB (JPG/PNG/GIF/WebP/MP4/MOV/PDF/SVG)', 'Category tags'],
        outputs: ['Searchable asset grid', 'Filter by type'],
        how: 'Drag and drop files into the Brand Assets uploader, then tag by category for fast retrieval.' },
      { id: 'templates', name: 'Templates Library', icon: '📐', shot: 'templates.jpg',
        what: 'Pre-built marketing and creative templates ready to clone and customise.',
        inputs: ['Filter by channel / format'],
        outputs: ['One-click clone into the relevant builder'],
        how: 'Pick a template, click Use, then edit in place.' },
      { id: 'creative', name: 'AI Creative Generation Engine', icon: '🎨', shot: 'creative.jpg',
        what: 'Generates ad copy and headlines benchmarked against real competitor performance.',
        inputs: ['Competitor intel', 'Generate More trigger'],
        outputs: ['Ad copy variants', 'Headline options', 'Campaign briefs'],
        how: 'Pick the competitor and channel, then click Generate. Iterate until you hit the angle you want.' },
      { id: 'smart-creative', name: 'Smart Creative Builder', icon: '✨', shot: 'smart-creative.jpg',
        what: 'Data-driven ad creative builder that combines copy, image and call-to-action against tested patterns.',
        inputs: ['Brand assets + product/offer context'],
        outputs: ['Multi-variant ad mockups ready for export'],
        how: 'Open Smart Creative, pick the format, and step through the builder.' },
      { id: 'carousel', name: 'Carousel Generator', icon: '🎠', shot: 'carousel.jpg',
        what: 'Creates multi-image carousel ads for social platforms automatically.',
        inputs: ['Topic + brand assets'],
        outputs: ['5-10 slide carousel ready to publish'],
        how: 'Type the topic, pick a style, and let it generate the slide deck.' },
      { id: 'ugc-avatars', name: 'AI UGC Avatars', icon: '🧑‍🎤', shot: 'ugc-avatars.jpg',
        what: 'Generates AI-based user-generated-content avatars for short video marketing.',
        inputs: ['Script + avatar selection'],
        outputs: ['Talking-head video clip'],
        how: 'Pick an avatar, paste a script, hit Generate — output downloads as MP4.' },
      { id: 'voiceovers', name: 'AI Voiceovers', icon: '🎙️', shot: 'voiceovers.jpg',
        what: 'Generates high-quality AI speech for ads and video content.',
        inputs: ['Script + voice + language'],
        outputs: ['Downloadable audio file'],
        how: 'Paste text, pick a voice, hit Generate.' },
      { id: 'voiceover', name: 'Voiceover Studio', icon: '🔊', shot: 'voiceover.jpg',
        what: 'Specialised studio for creating, editing and tuning AI-generated voiceovers.',
        inputs: ['Script + voice/style controls'],
        outputs: ['Polished voiceover audio'],
        how: 'Use Studio when you need finer control — pacing, emphasis, multi-take comparison.' },
      { id: 'video-script', name: 'Video Script Generator', icon: '🎬', shot: 'video-script.jpg',
        what: 'Drafts scripts for video ads and content based on goal and audience.',
        inputs: ['Topic + goal + length'],
        outputs: ['Hook, body and CTA-structured script'],
        how: 'Pick the goal (awareness / conversion), enter the topic, and refine.' },
      { id: 'content', name: 'Content AI', icon: '🧠', shot: 'content.jpg',
        what: 'General AI tool for generating marketing copy and articles.',
        inputs: ['Topic + brief + tone'],
        outputs: ['SEO-aware article draft'],
        how: 'Use the brief field to be specific — better briefs produce far better content.' },
      { id: 'headline-tester', name: 'Headline & Hook Tester', icon: '🎯', shot: 'headline-tester.jpg',
        what: 'Scores headlines across virality patterns and provides alternate variants.',
        inputs: ['Original headline'],
        outputs: ['Score + reasoning + 5 alternative headlines'],
        how: 'Paste a headline and review the alternatives before publishing.' },
      { id: 'press-release', name: 'AI Press Release Generator', icon: '📰', shot: 'press-release.jpg',
        what: 'Drafts AP-style press releases for launches and crisis responses.',
        inputs: ['Topic + key facts + quote'],
        outputs: ['Wire-ready press release'],
        how: 'Fill the brief — InfoGenie produces the AP-formatted release.' },
      { id: 'cold-email', name: 'AI Cold Email Writer', icon: '✉️', shot: 'cold-email.jpg',
        what: 'Drafts multi-step cold outreach sequences tailored to specific prospects.',
        inputs: ['Prospect / persona + offer'],
        outputs: ['3-5 email cadence ready to copy'],
        how: 'Describe the prospect; the writer builds the full sequence.' },
      { id: 'email-personalizer', name: 'AI Sales Email Personalizer', icon: '📨', shot: 'email-personalizer.jpg',
        what: 'Personalises base templates with research from each lead\'s company website.',
        inputs: ['Base template + lead URL'],
        outputs: ['Personalised email per lead'],
        how: 'Drop in a template and a lead URL — output is personalised in seconds.' },
      { id: 'reply-assistant', name: 'Reply Assistant', icon: '💬', shot: 'reply-assistant.jpg',
        what: 'Identifies unanswered mentions and drafts AI replies in your brand tone.',
        inputs: ['Saved brand persona (from ICP Studio)'],
        outputs: ['On-brand reply drafts ready to post'],
        how: 'Set up a persona once, then approve or edit each suggested reply.' },
      { id: 'chatbot-builder', name: 'Chatbot Builder', icon: '🤖', shot: 'chatbot-builder.jpg',
        what: 'Build and deploy AI-powered chatbots embedded on your site.',
        inputs: ['Knowledge base + tone + handoff rules'],
        outputs: ['Embeddable chat widget'],
        how: 'Step through the builder, then paste the embed snippet on your site.' },
      { id: 'localization', name: 'Localization (40+ languages)', icon: '🌍', shot: 'localization.jpg',
        what: 'Translates and adapts marketing content for over 40 languages — preserving brand voice.',
        inputs: ['Source text + target language'],
        outputs: ['Localised, culturally-adapted copy'],
        how: 'Paste copy, pick the language, hit Translate.' },
      { id: 'landing-builder', name: 'AI Landing Page Builder', icon: '🌐', shot: 'landing-builder.jpg',
        what: 'Generates full HTML landing pages including hero, features, FAQ and CTA from a brief.',
        inputs: ['Product / offer brief'],
        outputs: ['Hosted landing page + downloadable HTML'],
        how: 'Fill the brief, pick a style, click Build — the page deploys automatically.' },
      { id: 'schema-generator', name: 'Schema Generator', icon: '🏷️', shot: 'schema-generator.jpg',
        what: 'Creates JSON-LD schema markup to improve search visibility and rich-result eligibility.',
        inputs: ['Page type + entity details'],
        outputs: ['Copy-paste JSON-LD block'],
        how: 'Pick the schema type and fill the fields — the markup is generated immediately.' },
      { id: 'campaigns', name: 'Campaign Intelligence', icon: '🚀', shot: 'campaigns.jpg',
        what: 'AI-generated campaign improvements and structural recommendations with one-click launch.',
        inputs: ['Launch modal: budget, platform, region'],
        outputs: ['Automated deployment to Google, Meta, TikTok'],
        how: 'Click Launch Campaign on any recommendation to push the campaign live to your connected ad accounts.' },
      { id: 'social', name: 'Social Calendar & Generator', icon: '📅', shot: 'social.jpg',
        what: 'End-to-end social media management — generate posts, schedule, and visualise.',
        inputs: ['Create Post trigger (text/images)'],
        outputs: ['Visual calendar', 'Scheduled posts across platforms'],
        how: 'Use Create Post to draft content, set a publish time, and approve. Posts appear in the Master Calendar.' },
      { id: 'content-calendar', name: 'Content Calendar Auto-Pilot', icon: '🗓️', shot: 'content-calendar.jpg',
        what: 'Generates a multi-channel content calendar with hooks, copy and timing — for any window you pick.',
        inputs: ['Window (week / month / quarter) + channels'],
        outputs: ['Pre-populated calendar ready to schedule'],
        how: 'Pick the window and channels, click Generate, then approve or edit each entry.' },
      { id: 'studio', name: 'Creator Studio (all-in-one)', icon: '🎭', shot: 'studio.jpg',
        what: 'Single workspace bundling brand identity, AI image tools, video clips, slide decks, and email signatures — everything you need to ship a campaign without a designer.',
        inputs: ['Brand prompt or uploaded logo', 'Reference photo or empty canvas', 'Slide / signature topic'],
        outputs: ['Brand kit (logo, palette, fonts)', 'Generated/edited images & video', 'Slide deck PDF', 'HTML email signature'],
        how: 'Open Studio, pick a tile (Brand · Image · Video · Slides · Signature), fill the short form and click Generate. Outputs save to your asset library and can be reused in any campaign.' },
      { id: 'whatsapp', name: 'WhatsApp Channel', icon: '💬', shot: 'whatsapp.jpg',
        what: 'Two-way WhatsApp messaging through Meta\'s Cloud API — send templates or free-form replies, receive inbound messages straight into the unified inbox.',
        inputs: ['WhatsApp phone-number ID + access token (Settings)', 'Recipient number', 'Template name or text body'],
        outputs: ['Sent message status', 'Inbound message thread in inbox', 'Per-conversation history'],
        how: 'Connect your Meta WhatsApp Business number in Settings. Pick a recipient, choose a template (or type a free-form reply within the 24h window), and send. Replies arrive in your unified inbox automatically.' },
      { id: 'voice-caller', name: 'AI Voice Caller', icon: '📞', shot: 'voice-caller.jpg',
        what: 'Outbound AI phone calls via Vapi.ai — your AI agent dials the prospect, runs a scripted conversation, and logs the transcript + outcome.',
        inputs: ['Vapi API key + phone-number ID (Settings)', 'Recipient phone', 'Call script / objective'],
        outputs: ['Live call status', 'Full transcript', 'Outcome label (booked / not interested / callback)'],
        how: 'Drop the prospect number, paste your script (or use a template), click Call. Watch the live status; the transcript and outcome land in the calls table when the call ends.' },
      { id: 'site-builder', name: 'Site Builder (multi-page)', icon: '🧱', shot: 'site-builder.jpg',
        what: 'Block-based landing-page builder — assemble hero, features, testimonials, FAQ, CTA blocks into a public page hosted at /lp/:slug.',
        inputs: ['Page slug + title', 'Block selection + per-block content', 'Optional brand kit overlay'],
        outputs: ['Published landing page at a public URL', 'Form submissions routed to your inbox / HubSpot'],
        how: 'Click "+ New Page", give it a slug, drag in the blocks you want, fill the copy, then Publish. Share the /lp/:slug URL anywhere.' },
      { id: 'linksell', name: 'Link-in-Bio + Stripe', icon: '🛒', shot: 'linksell.jpg',
        what: 'Linktree-style bio page with built-in Stripe checkout — list links, products and digital goods at /bio/:slug. Buyers pay without leaving the page.',
        inputs: ['Bio slug + avatar + headline', 'Link list (label + URL)', 'Product list (name + price + Stripe price ID)'],
        outputs: ['Public bio page', 'Stripe checkout sessions', 'Order confirmations via Resend'],
        how: 'Pick a slug, add your links and products (with Stripe price IDs from your Stripe dashboard), then publish. Share /bio/:slug — buyers click a product, complete Stripe checkout, and receive a confirmation email automatically.' },
    ],
  },
  {
    nav: 'Reach',
    icon: '📡',
    color: C.purple,
    summary: 'Distribute content and ads to target audiences across every channel that matters.',
    features: [
      { id: 'audience', name: 'Audience Intelligence', icon: '🎯', shot: 'audience.jpg',
        what: 'Identifies and targets high-converting audience segments.',
        inputs: ['Auto-Target trigger'],
        outputs: ['Defined audience segments', 'Targeting parameters for ad platforms'],
        how: 'Click Auto-Target to let InfoGenie build your top 5 segments automatically. Push them straight to Meta, Google, or TikTok.' },
      { id: 'lookalike', name: 'Lookalike Audiences', icon: '👥', shot: 'lookalike.jpg',
        what: 'Creates new audience segments that mirror your best customers or competitor targets.',
        inputs: ['Seed audience or customer list'],
        outputs: ['Lookalike segment ready for paid platforms'],
        how: 'Pick a seed, choose the similarity tier, push to your ad account.' },
      { id: 'lead-finder', name: 'B2B Lead Finder', icon: '🧲', shot: 'lead-finder.jpg',
        what: 'Searches a database of 275M+ contacts for prospects matching your ICP.',
        inputs: ['Filters: industry, role, company size, geography'],
        outputs: ['Contact list with email + LinkedIn'],
        how: 'Set the filters, run the search, push selected leads to HubSpot.' },
      { id: 'lead-qualifier', name: 'Lead Qualifier', icon: '✅', shot: 'lead-qualifier.jpg',
        what: 'Automatically scores leads on firmographic and intent signals.',
        inputs: ['Lead list (from CRM or Lead Finder)'],
        outputs: ['BANT-style score per lead'],
        how: 'Run the qualifier — leads move into hot / warm / cold buckets automatically.' },
      { id: 'hubspot-sync', name: 'HubSpot Sync', icon: '🔄', shot: 'hubspot-sync.jpg',
        what: 'Pushes leads, influencers and dynamic audiences from InfoGenie directly into your HubSpot CRM.',
        inputs: ['HubSpot private app token (Settings)'],
        outputs: ['Synced contacts + lists in HubSpot'],
        how: 'Connect HubSpot once in Settings — sync runs on demand or on a schedule.' },
      { id: 'advertise', name: 'Multi-Channel Advertising Hub', icon: '📣', shot: 'advertise.jpg',
        what: 'Management interface for lead-generation ads across 20+ channels.',
        inputs: ['New Campaign trigger', 'Platform connections'],
        outputs: ['Integrated campaign management', 'Cross-platform performance tracking'],
        how: 'Connect your ad accounts in Settings, then use New Campaign to launch coordinated buys across selected platforms.' },
      { id: 'import-campaigns', name: 'Import Campaigns', icon: '📥', shot: 'import-campaigns.jpg',
        what: 'Connect and sync existing ad campaigns from external platforms into InfoGenie\'s optimiser.',
        inputs: ['Platform credentials'],
        outputs: ['Imported campaigns visible under Tracked Campaigns'],
        how: 'Click Import after connecting a platform — InfoGenie pulls the campaign tree.' },
      { id: 'opt-folders', name: 'Optimization Folders', icon: '📁', shot: 'opt-folders.jpg',
        what: 'Organise campaigns into logical groups for bulk AI optimisation.',
        inputs: ['Folder name + campaign assignments'],
        outputs: ['Folder-level optimisation rules'],
        how: 'Create a folder, assign campaigns, then attach optimisation rules at the folder level.' },
      { id: 'social-publisher', name: 'Social Publisher', icon: '📤', shot: 'social-publisher.jpg',
        what: 'Directly publishes content to connected social accounts.',
        inputs: ['Post content + platform + schedule'],
        outputs: ['Published or scheduled posts'],
        how: 'Compose, pick the platforms, schedule or publish.' },
      { id: 'ab-designer', name: 'AI A/B Test Designer', icon: '🧪', shot: 'ab-designer.jpg',
        what: 'Creates scientifically angled test variants with predicted lift before you run them.',
        inputs: ['Hypothesis + control element'],
        outputs: ['Variant set with predicted lift + sample-size guidance'],
        how: 'Describe the hypothesis — InfoGenie produces variants and tells you how long to run.' },
      { id: 'conversion-boosters', name: 'Conversion Boosters', icon: '🚀', shot: 'conversion-boosters.jpg',
        what: 'Drop-in widgets and patterns designed to lift on-page conversion rates.',
        inputs: ['Page type + goal'],
        outputs: ['Embeddable booster snippets'],
        how: 'Pick a booster, paste the snippet, monitor lift in CRO Lab.' },
      { id: 'discovery', name: 'Influencer Discovery', icon: '🔭', shot: 'discovery.jpg',
        what: 'Finds active creators in any niche via live web search.',
        inputs: ['Niche + region + platform'],
        outputs: ['Creator list with handles, audience size, engagement'],
        how: 'Search a niche — push promising creators to the CRM with one click.' },
      { id: 'influencers', name: 'Influencer CRM', icon: '🌟', shot: 'influencers.jpg',
        what: 'Pipeline tracker for creator partnerships, outreach and deal management.',
        inputs: ['Creator records + status changes'],
        outputs: ['Kanban-style pipeline'],
        how: 'Move creators through your pipeline; sync to HubSpot if needed.' },
      { id: 'search-intel', name: 'Search & AI Visibility', icon: '🔮', shot: 'search-intel.jpg',
        what: 'Monitors brand presence in AI engines like ChatGPT, Claude and Perplexity.',
        inputs: ['Brand + tracked prompts'],
        outputs: ['Citation tracking', 'Sentiment per engine'],
        how: 'Add the prompts you care about — InfoGenie polls the AI engines and flags drift.' },
      { id: 'geo-audit', name: 'GEO Audit (AI Engines)', icon: '🤖', shot: 'geo-audit.jpg',
        what: 'Audits how AI engines respond to brand queries in specific geographies.',
        inputs: ['Brand + region + prompt set'],
        outputs: ['Per-engine response transcript + citation analysis'],
        how: 'Pick the region and prompts, hit Audit, then export the report.' },
      { id: 'seo-auditor', name: 'SEO On-Page Auditor', icon: '🧭', shot: 'seo-auditor.jpg',
        what: 'Analyses individual pages for SEO best practice and technical issues.',
        inputs: ['Page URL'],
        outputs: ['Pass/fail checklist + fix suggestions'],
        how: 'Paste a URL — every issue includes a recommended fix.' },
      { id: 'seo-crawler', name: 'Site SEO Crawler', icon: '🕸️', shot: 'seo-crawler.jpg',
        what: 'Crawls entire websites to surface hidden SEO problems.',
        inputs: ['Root domain + crawl depth'],
        outputs: ['Per-page issue report', 'Site-wide health grade'],
        how: 'Start the crawl — issues are grouped by severity for triage.' },
      { id: 'seo-tasks', name: 'SEO Task Manager', icon: '📋', shot: 'seo-tasks.jpg',
        what: 'Organises and tracks SEO improvements and technical fixes as a Kanban board.',
        inputs: ['Tasks created from auditor / crawler'],
        outputs: ['Status-tracked task list'],
        how: 'Move tasks across columns as they\'re completed.' },
      { id: 'local-seo', name: 'Local SEO Basics', icon: '📍', shot: 'local-seo.jpg',
        what: 'Essential tools for managing local business listings and local search presence.',
        inputs: ['Business name + address + categories'],
        outputs: ['Listing-health checklist'],
        how: 'Fill the business profile and review the listings checklist.' },
      { id: 'web-vitals', name: 'Web Vitals Auditor', icon: '⚡', shot: 'web-vitals.jpg',
        what: 'Audits Core Web Vitals and Lighthouse scores for any URL.',
        inputs: ['Page URL'],
        outputs: ['CWV report + Lighthouse breakdown'],
        how: 'Paste a URL and run — fix the items flagged red first.' },
      { id: 'social-tags', name: 'Social Tags Audit', icon: '🔖', shot: 'social-tags.jpg',
        what: 'Checks Open Graph and Twitter card tags for proper social sharing.',
        inputs: ['Page URL'],
        outputs: ['Tag-by-tag pass/fail with the actual values'],
        how: 'Paste the URL — fix any missing tags before sharing widely.' },
      { id: 'deliverability', name: 'Email Deliverability Auditor', icon: '📬', shot: 'deliverability.jpg',
        what: 'Performs DNS lookups for SPF, DKIM and DMARC to ensure email delivery.',
        inputs: ['Sending domain'],
        outputs: ['SPF / DKIM / DMARC status + fix suggestions'],
        how: 'Paste the domain — copy any missing DNS records straight from the result.' },
      { id: 'seo-widget', name: 'Embeddable Audit Widget', icon: '🧩', shot: 'seo-widget.jpg',
        what: 'A lead-capture widget that provides SEO audits to your site visitors.',
        inputs: ['Branding + lead-capture fields'],
        outputs: ['Embed snippet for your site'],
        how: 'Configure the widget, paste the snippet, harvest the leads.' },
      { id: 'unified-inbox', name: 'Unified Inbox', icon: '📬', shot: 'unified-inbox.jpg',
        what: 'Aggregates messages and mentions from multiple channels into one inbox.',
        inputs: ['Connected channels'],
        outputs: ['Single threaded inbox'],
        how: 'Connect your channels — every conversation lands here.' },
      { id: 'alert-routing', name: 'Smart Alert Routing', icon: '🔔', shot: 'alert-routing.jpg',
        what: 'Routes crisis, share-of-voice and digest alerts to Slack and email based on rules.',
        inputs: ['Slack webhook + email + rule set'],
        outputs: ['Routed alerts in real time'],
        how: 'Define rules once — the right alert goes to the right place automatically.' },
      { id: 'digest', name: 'AI Daily Digest', icon: '📋', shot: 'digest.jpg',
        what: 'One-page executive summary of crisis, trends and competitor activity — every morning.',
        inputs: ['Auto-pulled signals'],
        outputs: ['Daily PDF / inbox digest'],
        how: 'Subscribe once — the digest lands in your inbox every morning.' },
      { id: 'tiktok-downloader', name: 'TikTok Downloader', icon: '⬇️', shot: 'tiktok-downloader.jpg',
        what: 'Downloads TikTok videos for creative research and archival.',
        inputs: ['TikTok video URL'],
        outputs: ['Downloadable MP4'],
        how: 'Paste the URL and click Download.' },
      { id: 'audiences-dynamic', name: 'Dynamic Audiences (live)', icon: '🔄', shot: 'audiences-dynamic.jpg',
        what: 'Real-time rule-based contact segments that re-evaluate every 15 minutes — push them straight to a HubSpot list or bind them to a drip sequence.',
        inputs: ['Rule builder (field · operator · value)', 'Optional drip-sequence binding', 'Optional HubSpot list mirror'],
        outputs: ['Live member count + preview', 'Auto-enrolled drip campaign sends', 'Mirrored HubSpot static list'],
        how: 'Click "+ New Audience", chain the rules you want (e.g. last_seen < 7d AND plan = "free"), preview the matching contacts, then bind a drip and/or mirror to HubSpot. The 15-min cron keeps membership live.' },
      { id: 'journey-builder', name: 'Customer Journey Builder', icon: '🛤️', shot: 'journey-builder.jpg',
        what: 'Visual multi-step automation — chain trigger / wait / condition / action nodes to send email, SMS, WhatsApp, AI voice or web push as a contact progresses.',
        inputs: ['Trigger (signal, audience join, manual)', 'Wait + condition nodes', 'Action nodes (email/SMS/WhatsApp/voice/push/tag)'],
        outputs: ['Active journey runs per contact', 'Per-step delivery log', 'Pause/Activate state per journey'],
        how: 'Click "+ New Journey", drag the nodes onto the canvas, wire them, and Activate. The 60-second runner advances every contact whose next step is due.' },
      { id: 'omnichannel', name: 'Omnichannel Composer', icon: '📡', shot: 'omnichannel.jpg',
        what: 'Write the message once, fan it out across Email + SMS + WhatsApp + AI Voice + Web Push in a single send. Each channel\'s configuration status is shown up-front.',
        inputs: ['Audience or contact list', 'Channel checklist', 'Subject + body (with per-channel overrides)'],
        outputs: ['Per-channel send status', 'Per-contact delivery breakdown', 'Bounces / failures isolated per channel'],
        how: 'Pick the audience, tick the channels you have wired (greyed if not configured), write your message, click Send. Each contact gets one send per channel; one failure never aborts the whole batch.' },
      { id: 'bookings', name: 'Bookings (public scheduler)', icon: '📅', shot: 'bookings.jpg',
        what: 'Calendly-style public booking page — define your availability, share the link, and prospects self-book a slot with automatic confirmation emails.',
        inputs: ['Availability windows + slot length', 'Public slug + meeting type', 'Required form fields'],
        outputs: ['Booked appointments in your dashboard', 'Confirmation emails to both parties (Resend)', 'Optional ICS calendar attachment'],
        how: 'Set your weekly availability once, pick a slug, share the public link. Bookings land in the dashboard and trigger a confirmation email automatically.' },
    ],
  },
  {
    nav: 'Grow',
    icon: '📈',
    color: C.green,
    summary: 'Optimise visibility, automate execution and measure long-term performance.',
    features: [
      { id: 'goals', name: 'Goals & Targets', icon: '🎯', shot: 'goals.jpg',
        what: 'Define and track your primary business and marketing KPIs.',
        inputs: ['Goal definitions + targets + windows'],
        outputs: ['Progress chart + variance to target'],
        how: 'Set goals once — the platform tracks variance automatically.' },
      { id: 'kpi-tracker', name: 'KPI Tracker', icon: '📐', shot: 'kpi-tracker.jpg',
        what: 'Long-term performance tracking against business goals.',
        inputs: ['Data from connected ad/analytics accounts'],
        outputs: ['Growth-trend visualisations', 'Goal-completion charts'],
        how: 'Set your goals once, then check progress weekly. Anomalies are flagged automatically.' },
      { id: 'action-center', name: 'Action Center', icon: '⚡', shot: 'action-center.jpg',
        what: 'Marketing-command view showing upcoming launches and system risks.',
        inputs: ['Refresh trigger'],
        outputs: ['Live status feed', 'Upcoming milestones', 'Optimisation opportunities'],
        how: 'Visit daily as your single pane of glass. Click any item to jump to the relevant module.' },
      { id: 'autoseo', name: 'AutoSEO Pro', icon: '🚀', shot: 'autoseo.jpg',
        what: 'Automated SEO execution — article generation, on-page fixes and backlink tracking.',
        inputs: ['WordPress credentials (API)', 'Target keywords'],
        outputs: ['Published articles', 'Backlink reports', 'Keyword research'],
        how: 'Connect WordPress in Settings, choose target keywords, and let AutoSEO publish optimised articles on a schedule.' },
      { id: 'contentscorer', name: 'Content Scorer', icon: '📝', shot: 'contentscorer.jpg',
        what: 'Grades existing content against SEO and readability benchmarks.',
        inputs: ['Page URL or pasted text'],
        outputs: ['Score + ranked improvement list'],
        how: 'Paste the content, review the score, fix the items at the top of the list.' },
      { id: 'link-suggester', name: 'Internal Link Suggester', icon: '🔗', shot: 'link-suggester.jpg',
        what: 'AI recommendations for building an internal-link structure that lifts site authority.',
        inputs: ['Source page URL'],
        outputs: ['Suggested target pages + anchor text'],
        how: 'Run on each new piece of content — apply the top suggestions in your CMS.' },
      { id: 'cro-lab', name: 'CRO Lab', icon: '🧪', shot: 'cro-lab.jpg',
        what: 'Hub for managing and analysing conversion-rate-optimisation experiments.',
        inputs: ['Experiment definitions + traffic split'],
        outputs: ['Statistical lift + winning variant'],
        how: 'Define the experiment, monitor lift, ship the winner.' },
      { id: 'ai-audit-suite', name: 'AI Audit Suite', icon: '🔬', shot: 'ai-audit-suite.jpg',
        what: 'Independent deep-dive audits for various AI-performance metrics.',
        inputs: ['Audit selection (Prompt Coverage, Entity Mapping, etc.)'],
        outputs: ['Reports on answer accuracy, AI Overviews, citation-to-traffic attribution'],
        how: 'Pick the audit type and click Run. Reports save to the Action Center for follow-up.' },
      { id: 'aivisibility', name: 'AI Visibility Intelligence', icon: '🤖', shot: 'aivisibility.jpg',
        what: 'Tracks how your brand is cited by LLMs (ChatGPT, Claude, Gemini, Perplexity).',
        inputs: ['Run AI Audit trigger'],
        outputs: ['Citation tracking', 'Brand sentiment in AI responses', 'Optimisation recommendations'],
        how: 'Click Run AI Audit. The dashboard shows where you appear (and where you don\'t) in AI answer engines.' },
      { id: 'meta-insights', name: 'Meta Ads Insights', icon: '📘', shot: 'meta-insights.jpg',
        what: 'Live performance data from your Meta Ads account — spend, ROAS, top creatives.',
        inputs: ['Meta access token (Settings)'],
        outputs: ['Live spend / ROAS chart + top ad list'],
        how: 'Connect Meta in Settings — data refreshes hourly.' },
      { id: 'google-ads-insights', name: 'Google Ads Insights', icon: '🅖', shot: 'google-ads-insights.jpg',
        what: 'Real-time performance metrics and top-ad tracking for Google Ads.',
        inputs: ['Google Ads OAuth (Settings)'],
        outputs: ['Live spend, conversions, top ads'],
        how: 'Connect Google Ads in Settings — the optimiser uses this feed too.' },
      { id: 'tiktok-ads-insights', name: 'TikTok Ads Insights', icon: '🎵', shot: 'tiktok-ads-insights.jpg',
        what: 'Spend, ROAS and campaign performance from the TikTok Marketing API.',
        inputs: ['TikTok access token + advertiser ID (Settings)'],
        outputs: ['Spend / ROAS / video metrics'],
        how: 'Connect TikTok in Settings to surface live ad data.' },
      { id: 'social-analytics', name: 'Social Analytics', icon: '📊', shot: 'social-analytics.jpg',
        what: 'Aggregated performance data across all connected social channels.',
        inputs: ['Connected social accounts'],
        outputs: ['Per-channel reach, engagement, follower trend'],
        how: 'Connect channels — the dashboard rebuilds automatically.' },
      { id: 'optimizer', name: 'AI Optimizer', icon: '🤖', shot: 'optimizer.jpg',
        what: '24/7 reinforcement-learning engine that optimises ad campaigns automatically.',
        inputs: ['Connected ad accounts + risk thresholds'],
        outputs: ['PAUSE / SCALE / HOLD recommendations every 6 hours'],
        how: 'Start in dry-run, review the moves, then flip to live mode when comfortable.' },
      { id: 'analytics-hub', name: 'GSC / GA4 Hub', icon: '📡', shot: 'analytics-hub.jpg',
        what: 'Integrated view of Google Search Console and Google Analytics 4 data.',
        inputs: ['GSC + GA4 OAuth (Settings)'],
        outputs: ['Search query + landing-page performance'],
        how: 'Connect GSC and GA4 in Settings — the hub merges both feeds.' },
      { id: 'amplitude-agents', name: 'Amplitude AI Agents', icon: '📶', shot: 'amplitude-agents.jpg',
        what: 'AI-powered analysis of user behaviour and product usage from Amplitude.',
        inputs: ['Amplitude API key'],
        outputs: ['Funnel insights + behavioural cohorts'],
        how: 'Connect Amplitude — the agents surface insights you would normally miss.' },
      { id: 'blended-perf', name: 'Blended Performance', icon: '💎', shot: 'blended-perf.jpg',
        what: 'Unified view of performance across all paid and organic channels.',
        inputs: ['Connected ad + analytics accounts'],
        outputs: ['Blended CAC, ROAS and revenue chart'],
        how: 'Use weekly to see the big picture across every channel.' },
      { id: 'attribution', name: 'Attribution & ROI', icon: '🧮', shot: 'attribution.jpg',
        what: 'Multi-touch attribution to determine the true ROI per channel.',
        inputs: ['Tracked conversions + channel data'],
        outputs: ['Per-channel attributed revenue + ROI'],
        how: 'Compare attribution windows to see which channel really drives revenue.' },
      { id: 'true-roas', name: 'True ROAS', icon: '💰', shot: 'true-roas.jpg',
        what: 'Accurate ROAS calculation by blending ad spend with real-time revenue.',
        inputs: ['Spend feed + revenue feed'],
        outputs: ['True ROAS vs platform-reported ROAS'],
        how: 'Use to spot platforms inflating their attributed revenue.' },
      { id: 'churn-scorer', name: 'Predictive Churn Scorer', icon: '⚠️', shot: 'churn-scorer.jpg',
        what: 'AI predicts which customers are at risk of leaving based on activity patterns.',
        inputs: ['Customer activity data'],
        outputs: ['Risk score per customer + reasons'],
        how: 'Run weekly — push high-risk customers into a Re-Engage drip.' },
      { id: 'growth-methodology', name: 'Growth Methodology (5-stage)', icon: '🎯', shot: 'growth-methodology.jpg',
        what: 'The InfoGenie methodology page — Awareness → Acquisition → Activation → Retention → Revenue with the named tools that map to each stage.',
        inputs: ['Read-only — sourced from the platform tier index'],
        outputs: ['Per-stage tool list', 'Recommended weekly cadence', 'KPI examples'],
        how: 'Open at the start of each quarter to confirm you have a tool firing in every stage of the funnel.' },
    ],
  },
  {
    nav: 'Manage',
    icon: '⚙️',
    color: C.amber,
    summary: 'Operations, reporting, and platform configuration.',
    features: [
      { id: 'master-calendar', name: 'Master Calendar', icon: '🗓️', shot: 'master-calendar.jpg',
        what: 'Unified view of all scheduled marketing activity — campaigns, content, social, launches.',
        inputs: ['Auto-sync from other modules'],
        outputs: ['Global timeline of marketing operations'],
        how: 'Open Master Calendar to see every scheduled action. Click any item to edit in its source module.' },
      { id: 'launches', name: 'Launch Calendar', icon: '🚀', shot: 'launches.jpg',
        what: 'Specific timeline for product and feature releases.',
        inputs: ['Launch records (name, date, owner)'],
        outputs: ['Launch-only calendar view'],
        how: 'Add each launch — InfoGenie reminds you of upcoming releases.' },
      { id: 'reengage', name: 'Re-Engage', icon: '🔁', shot: 'reengage.jpg',
        what: 'Tools for customer retention and win-back campaigns.',
        inputs: ['Customer data segments'],
        outputs: ['Re-engagement campaign automation'],
        how: 'Upload or pull a customer list, choose a segment, and launch a re-engagement sequence.' },
      { id: 'automations', name: 'Automations', icon: '⚡', shot: 'automations.jpg',
        what: 'Workflow builder for connecting different parts of the marketing stack.',
        inputs: ['Trigger / Action definitions'],
        outputs: ['Cross-platform automated workflows'],
        how: 'Pick a trigger (e.g. competitor budget surge) and link it to an action (e.g. increase Meta bids).' },
      { id: 'stakeholders', name: 'Stakeholders', icon: '👤', shot: 'stakeholders.jpg',
        what: 'Manage team members and external partners involved in your marketing operation.',
        inputs: ['Person records + roles'],
        outputs: ['Stakeholder directory'],
        how: 'Add people once — assign owners on tasks across the platform.' },
      { id: 'meeting-notes', name: 'AI Meeting Note Summariser', icon: '📝', shot: 'meeting-notes.jpg',
        what: 'Summarises sales-call transcripts, generates BANT scoring and pulls out action items.',
        inputs: ['Pasted transcript or recording'],
        outputs: ['Summary + BANT score + action list'],
        how: 'Drop a transcript, get the summary in seconds.' },
      { id: 'results', name: 'Campaign Results & Action History', icon: '📋', shot: 'results.jpg',
        what: 'Live tracking of all platform-initiated actions and their measurable impact.',
        inputs: ['Export PDF trigger'],
        outputs: ['PDF reports', 'Historical action logs', 'Performance lift summaries'],
        how: 'Filter by date range and click Export PDF for a board-ready summary.' },
      { id: 'weekly-report', name: 'Weekly Auto-PDF Report', icon: '📑', shot: 'weekly-report.jpg',
        what: 'Auto-aggregates weekly brand performance into a PDF, emailed every Monday.',
        inputs: ['Recipient list'],
        outputs: ['Branded weekly PDF in their inbox'],
        how: 'Set the recipients once — InfoGenie ships the report every Monday morning.' },
      { id: 'cross-channel', name: 'Cross-Channel Report', icon: '🌐', shot: 'cross-channel.jpg',
        what: 'Comparative analysis across multiple marketing platforms in one view.',
        inputs: ['Connected ad + organic accounts'],
        outputs: ['Side-by-side channel comparison'],
        how: 'Use to spot which channels are pulling their weight and which aren\'t.' },
      { id: 'csuite', name: 'C-Suite Executive Reports', icon: '👔', shot: 'csuite.jpg',
        what: 'Role-specific board-ready dashboards (CEO / CMO / CFO / COO).',
        inputs: ['Role selection'],
        outputs: ['Executive PDF reports'],
        how: 'Pick the role lens, click Generate, download the board-ready PDF.' },
      { id: 'white-label', name: 'White-Label Reports', icon: '🎨', shot: 'white-label.jpg',
        what: 'Customisable reporting templates for agencies to present to clients under their own brand.',
        inputs: ['Logo + colours + cover content'],
        outputs: ['Branded PDF report'],
        how: 'Upload your branding once — every report can be re-skinned in one click.' },
      { id: 'bulk-reports', name: 'Bulk Reporting', icon: '📦', shot: 'bulk-reports.jpg',
        what: 'Generate and export multiple reports simultaneously for large accounts.',
        inputs: ['Account selection + report type'],
        outputs: ['Batch ZIP of PDFs'],
        how: 'Select the accounts, click Generate — download the ZIP when ready.' },
      { id: 'agency', name: 'Agency Hub & Reports', icon: '🏢', shot: 'agency.jpg',
        what: 'Multi-client management and white-label reporting interface.',
        inputs: ['Client account configurations'],
        outputs: ['Branded client reports', 'Multi-tenant dashboard'],
        how: 'Add clients in Settings, then switch context using the client dropdown to manage their campaigns separately.' },
      { id: 'technical-suite', name: 'Technical Suite', icon: '🛠️', shot: 'technical-suite.jpg',
        what: 'Technical SEO and site-health audits.',
        inputs: ['Run All Audits trigger'],
        outputs: ['Crawlability scores', 'Index-readiness report', 'Technical health grade'],
        how: 'Click Run All Audits to execute the full technical sweep. Each finding includes a fix.' },
      { id: 'workspaces', name: 'Workspaces & Team', icon: '👥', shot: 'workspaces.jpg',
        what: 'Manage collaborative spaces and team permissions.',
        inputs: ['Workspace + member invites'],
        outputs: ['Per-workspace data isolation + roles'],
        how: 'Create a workspace per client or brand; invite the relevant team members.' },
      { id: 'brand-calendar', name: 'Brand Calendar (10 categories)', icon: '📅', shot: 'brand-calendar.jpg',
        what: 'Unified marketing planner — one month-grid view across Brand, Email, SMS+WhatsApp, Social, Content, Ads, Event, Surveys, Website and your own activities.',
        inputs: ['Category filter (sidebar)', 'Click-to-add modal: title · category · date · notes'],
        outputs: ['Cross-category calendar grid', 'Per-day item count', 'Items persisted in brand_calendar_items table'],
        how: 'Open Brand Calendar, tick the categories you care about, click any day to add an item. Filter the sidebar to focus on one channel at a time.' },
      { id: 'budget-board', name: 'Budget Board (monitor + spend)', icon: '💰', shot: 'budget-board.jpg',
        what: 'Per-month spend tracker — set a target, allocate per channel (paid social, search, content, etc), log spend, and see actual vs target with a 30-day trend chart.',
        inputs: ['Monthly target', 'Per-channel allocation %', 'Manual or API spend entries'],
        outputs: ['Target vs actual gauge', 'Per-channel utilisation bars', '30-day spend trendline'],
        how: 'Set the month\'s target on the 1st, allocate across channels, then log spend as it happens (or let the optimizer mirror its outflows automatically).' },
      { id: 'web-analytics', name: 'Web Analytics (acquisition + behaviour)', icon: '📈', shot: 'web-analytics.jpg',
        what: 'Read-only aggregator that surfaces what InfoGenie can already see without GA4 — channel sessions/impressions from ad insights, top landing pages, mobile PageSpeed scores.',
        inputs: ['Auto-pulled from ad_insights, landing_pages, web_vitals (last 30d)'],
        outputs: ['Channel sessions table', 'Top landing pages list', 'Mobile PageSpeed scores per page'],
        how: 'Open it any time for a fast read of what is already being captured. Connect GA4 in Settings to unlock full Source/Medium and Country breakdowns.' },
      { id: 'team-meetings', name: 'Minutes of Meeting (AI Team)', icon: '📋', shot: 'team-meetings.jpg',
        what: 'Auto-generated meeting minutes for your AI executive team — summarises what each officer (Marketing, Sales, Analyst, etc.) executed in the last 24 hours.',
        inputs: ['Date range', 'Officer filter (optional)'],
        outputs: ['Per-officer activity log', 'Decision list', 'Open action items'],
        how: 'Open every morning to see what your AI team did overnight. Forward the summary to stakeholders or copy it into your standup notes.' },
      { id: 'playbook-7day', name: '7-Day Marketing Playbook', icon: '📅', shot: 'playbook-7day.jpg',
        what: 'A strategic-plan checklist (Day 1 Research → Day 7 Reporting) with an AI Suggest button on every step and a ▶ Run Autonomously option that appends each step as a real task on the matching AI officer.',
        inputs: ['Pick a day or click "Run All 7"', 'AI Suggest per step (optional)'],
        outputs: ['Per-step headline + rationale + 3-5 actions + KPI + risk', 'Tasks created on AI officers', 'Run history kept in playbook_7day_runs_v1'],
        how: 'New every Monday: open Day 1, click 🤖 AI Suggest for live recommendations, then ▶ Run Autonomously to dispatch the work. Repeat through Day 7 — or hit "Run All 7" once.' },
      { id: 'signal-triggers', name: 'Real-time Signal Triggers', icon: '⚡', shot: 'signal-triggers.jpg',
        what: 'Bridge between observable events (mention spike, sentiment drop, competitor price change, trending keyword, negative review, crisis alert, manual) and an automated journey enrolment.',
        inputs: ['Trigger type + match condition', 'Target journey to enrol contact in', 'Enabled / disabled toggle'],
        outputs: ['New journey runs spawned per matched signal', 'Manual fire UI for testing', 'Per-trigger fire history'],
        how: 'Pick a signal type, set the match condition, link it to a journey, enable. The trigger fires automatically when the signal hits, or use the manual fire button to test.' },
      { id: 'settings', name: 'Integrations & Settings', icon: '⚙️', shot: 'settings.jpg',
        what: 'Configuration panel for the entire platform.',
        inputs: ['API keys, AI model selection, account permissions'],
        outputs: ['Connected platform status', 'Global system configuration'],
        how: 'Connect Google Ads, Meta, TikTok, RapidAPI, OpenAI/Anthropic, HubSpot and other integrations from one screen.' },
    ],
  },
  {
    nav: 'AI Team',
    icon: '👥',
    color: C.purple,
    summary: 'Your virtual executive team — autonomous AI officers that watch the platform and act on your behalf.',
    features: [
      { id: 'ai-team', name: 'Team Roster', icon: '👥', shot: 'ai-team.jpg',
        what: 'The roster of every AI officer on your team — Marketing, Sales, Analyst, Content, SEO, CRO, Finance, Operations — each with a job description, KPIs and recent activity.',
        inputs: ['Click any officer card to drill into their tasks + history'],
        outputs: ['Per-officer status (active / paused)', 'Recent task list', 'KPI snapshot per officer'],
        how: 'Open Team Roster once a week to confirm every officer is live and producing output. Pause any officer you want to manage manually for a while.' },
      { id: 'finance-officer', name: 'Finance Officer', icon: '💼', shot: 'finance-officer.jpg',
        what: 'AI officer focused on cost discipline — watches spend vs target across the Budget Board, flags channel overruns, and recommends reallocations.',
        inputs: ['Budget Board targets + actuals (auto-pulled)', 'Optional pinned guardrails'],
        outputs: ['Daily spend digest', 'Overrun alerts with recommended fix', 'Reallocation proposals'],
        how: 'Set the monthly target on Budget Board, then let Finance Officer monitor automatically. Approve or dismiss its proposals from its task feed.' },
      { id: 'ops-officer', name: 'Operations Officer', icon: '🛠️', shot: 'ops-officer.jpg',
        what: 'AI officer focused on platform health — confirms integrations are connected, schedulers are firing, drips are delivering, and webhooks are not stuck.',
        inputs: ['Auto-monitored — checks every connected integration'],
        outputs: ['Daily ops digest', 'Per-integration health status', 'Specific fix recommendations when something is broken'],
        how: 'Check the Ops Officer feed any morning a number looks off — it usually already knows which integration is down and how to fix it.' },
    ],
  },
];

// Flat VIEWS list derived from SECTIONS — used by capture_screenshots.js.
const VIEWS = [];
SECTIONS.forEach(s => s.features.forEach(f => {
  VIEWS.push({ id: f.id, file: f.shot });
}));

module.exports = { SECTIONS, VIEWS, C };
