/* eslint-disable */
// One-line "Why it matters / when to use it" tagline per feature, rendered
// directly under the WHAT IT DOES paragraph in the PDF user manual. Keep each
// entry short (15-30 words) so the feature page does not spill onto a second
// page. If a key is missing, the renderer simply skips the line.
module.exports = {
  // ── Getting Started ──────────────────────────────────────────────────────
  'home': 'Use this every time you start a new analysis — one click here is what powers the dashboards, audiences and campaigns in every other tab.',
  'roadmap': 'Best for your first week on the platform — the roadmap stops you wandering and gets you to a live, optimised account in days, not months.',

  // ── Analyse ──────────────────────────────────────────────────────────────
  'dashboard': 'Your "30-second daily check" — open it first thing each morning to see whether your numbers are trending up or down vs. the competition.',
  'competitors': 'Use when you suspect a rival is gaining ground — the threat scoring tells you exactly where they are winning and what to do about it.',
  'intelligence': 'Best for spotting moves before they hit your revenue — alerts fire when a competitor changes pricing, launches a campaign or shifts ad spend.',
  'battleplan': 'Read this once after every analysis run — it converts the raw competitor data into a prioritised 90-day action list any team can execute.',
  'battle-cards': 'Hand these to sales before any pitch — a one-page intel brief on how to position against, and win deals over, each named rival.',
  'ad-library': 'Best for stealing the angles that already work — see live creative from rivals across 5 networks without paying for a separate spy tool.',
  'tech-stack': 'Use to spot what tools competitors actually pay for — a fast way to size their marketing budget and uncover gaps in your own stack.',
  'pricing-watch': 'Set this up the moment you suspect a rival is undercutting you — automated price alerts protect your margin without daily manual checks.',
  'job-board-spy': 'Best leading indicator of strategy shifts — when a competitor hires 10 SDRs you know they are about to attack a new segment.',
  'sov-tracker': 'Use to prove (or disprove) marketing impact to the board — share-of-voice trend lines are the cleanest way to show category dominance.',
  'crisis-radar': 'Indispensable if your brand is consumer-facing — catch a PR fire in the first 30 minutes instead of finding out from the news.',
  'icp-studio': 'Run this before every campaign launch — a sharp ICP halves wasted ad spend and dramatically improves the quality of inbound leads.',
  'voc': 'Best for finding your next product feature or marketing angle — your customers are already telling you what to build, this surfaces it.',
  'review-aggregator': 'Use weekly to catch reputation drift early — one bad week of reviews silently tanks conversion long before you spot it in revenue.',
  'glassdoor': 'A quiet tell on whether a rival is healthy or fragile — internal culture problems show up here months before they hit performance.',
  'mentions': 'Use to never miss a brand conversation — every blog post, news article and forum thread mentioning you in one searchable feed.',
  'reddit': 'Best for B2C and prosumer brands — Reddit is where buyers actually research, and unanswered threads here are pure pipeline opportunity.',
  'reddit-pulse': 'Use weekly to see if your brand is gaining or losing traction in community discussion — sentiment movement here usually predicts review-site movement.',
  'twitter-pulse': 'Best for live event marketing and crisis response — X is where breaking news, viral moments and customer complaints happen first.',
  'quora-mining': 'Use to find evergreen content ideas — every Quora question is a Google query someone is typing right now and not finding good answers for.',
  'youtube-monitor': 'Best for tracking competitor video strategy — view-velocity tells you which uploads are working so you can copy the format, not the content.',
  'podcast-monitor': 'Use for high-intent earned-media tracking — when a podcaster mentions you, their audience is the most pre-qualified traffic you will ever get.',
  'newsletter-tracker': 'Best for stealing email angles that already convert — competitor subject lines are a free A/B test of what their audience opens.',
  'trending-topics': 'Use before every content sprint — riding a trending topic in the first 48 hours can 10x your reach versus the same content a week late.',
  'content-gaps': 'The single fastest way to grow organic traffic — every gap keyword is search intent your competitors monetise and you currently do not.',
  'intent-map': 'Use to stop writing the wrong content for the wrong query — informational pages cannot rank for transactional intent and vice versa.',
  'keyword-map': 'Best for sites with 50+ pages — without an explicit map your own pages compete with each other and dilute rankings (cannibalisation).',
  'keyword-explorer': 'Use whenever you are scoping a new content series — pick the long-tail variants with low difficulty for the fastest path to ranked traffic.',
  'serp': 'Best for understanding why you do or do not rank — see exactly which competitors, ads and answer-boxes are above you for any query.',
  'serp-tracker': 'Use this on your top 20 money-keywords — daily rank changes are the earliest warning that an algorithm update or a new rival is hurting you.',
  'backlinks': 'Best for sizing the link gap before you invest in outreach — knowing a competitor has 5x your backlinks is what scopes a realistic catch-up plan.',
  'backlink-monitor': 'Use to protect hard-won links — a lost backlink can drop a ranking page out of the top 10 within 48 hours if you do not replace it.',

  // ── Create ───────────────────────────────────────────────────────────────
  'brand-assets': 'Use as your single source of truth — when copy and creative come from one tagged library, every campaign launches on-brand without back-and-forth.',
  'templates': 'Best for cutting concept-to-launch time from days to minutes — start from a proven structure instead of a blank page on every brief.',
  'creative': 'Use whenever you need 10 ad variants by tomorrow — the engine drafts copy benchmarked against ads that are already performing in your category.',
  'smart-creative': 'Best for paid social where creative fatigue kills ROAS — Smart Creative builds variants tuned to patterns that historically beat the average.',
  'carousel': 'Use when you have a story that does not fit one image — multi-slide carousels consistently out-perform single-image posts on Meta and LinkedIn.',
  'ugc-avatars': 'Best for testing video angles without a film crew — produce 10 talking-head variants in an hour to see which message and tone wins.',
  'voiceovers': 'Use for fast voiceover layers on social and ad creative — generate broadcast-quality narration without booking talent or a studio.',
  'voiceover': 'Best when broadcast quality matters — Studio gives you scene-by-scene control over pacing, emphasis and multi-take comparison before export.',
  'video-script': 'Use before every video shoot — a structured hook-body-CTA script is the difference between a 3-second scroll and a 30-second watch.',
  'content': 'Best for getting a publishable first draft fast — pair the AI output with one human edit pass for the quality bar your readers expect.',
  'headline-tester': 'Use on every blog post and ad — a 20% lift in headline quality compounds into 20% more clicks on every piece of content you ship.',
  'press-release': 'Best for product launches, fundraising and crisis responses — a wire-ready release written in minutes, not the half-day a freelancer would take.',
  'cold-email': 'Use to scale outbound without losing personalisation — multi-step cadences cover the prospects who never reply on email one alone (which is most of them).',
  'email-personalizer': 'Best for SDR teams burning out on manual research — auto-personalisation lifts reply rates roughly 3x without adding headcount.',
  'reply-assistant': 'Use when your unanswered-mention pile is growing — drafted replies in your tone mean the team approves instead of writing from scratch.',
  'chatbot-builder': 'Best for sites where the same questions cost you sales every day — an embedded bot answers them at 2am and books demos while you sleep.',
  'localization': 'Use before any market expansion — a literal translation will lose every customer; cultural adaptation is what makes copy actually convert.',
  'landing-builder': 'Best when paid traffic is waiting for a page — a purpose-built landing page typically converts 2-5x better than sending traffic to your homepage.',
  'schema-generator': 'Use to qualify for rich results and AI citations — search engines and LLMs both rely on schema to know what your page is actually about.',
  'campaigns': 'Best for closing the gap between insight and action — every recommendation has a one-click launch so no good idea dies in a Slack thread.',
  'social': 'Use as your content command center — visualising every channel on one calendar is what catches gaps and double-posts before they go live.',
  'content-calendar': 'Best for solo marketers and small teams — auto-pilot eliminates the weekly "what should we post?" meeting and keeps cadence consistent.',

  // ── Reach ────────────────────────────────────────────────────────────────
  'audience': 'Use as the first step before any paid campaign — wrong audience is the #1 reason ad budgets get burned without producing pipeline.',
  'lookalike': 'Best for scaling what already works — lookalikes consistently out-perform broad targeting once your seed audience exceeds about 1,000 customers.',
  'audiences-dynamic': 'Use to keep nurture flows automatically clean — contacts join and leave segments based on behaviour so you never email the wrong list.',
  'lead-finder': 'Best for filling pipeline this quarter — pull a clean list matching your ICP in minutes instead of paying a list broker by the row.',
  'lead-qualifier': 'Use before every sales handoff — automated BANT scoring stops AEs wasting hours on leads that were never going to close.',
  'hubspot-sync': 'Best for keeping the rest of your stack in sync — every audience and lead found in InfoGenie should land in HubSpot the same hour.',
  'advertise': 'Use as your one console for paid media — managing 20 platforms in 20 tabs is how budget overruns and tracking gaps happen.',
  'import-campaigns': 'Best when you already run paid ads elsewhere — pull the existing tree in once and the AI optimiser starts learning from day one.',
  'opt-folders': 'Use for portfolios with 50+ campaigns — folder-level rules apply optimisations across grouped campaigns instead of one at a time.',
  'social-publisher': 'Best for teams scheduling daily — bulk publish to all your channels at once instead of manually copying the same post 6 times.',
  'ab-designer': 'Use before every test — knowing the predicted lift and required sample size up-front stops you killing tests too early or too late.',
  'conversion-boosters': 'Best for sites with traffic but soft conversion — drop-in widgets like exit intent and social proof typically lift CR by 10-20% in a week.',
  'discovery': 'Use whenever you scope an influencer campaign — a fresh creator search beats reusing the same 10 names every brand in your category already worked with.',
  'influencers': 'Best for managing 5+ creator partnerships at once — a kanban pipeline stops promising creators going cold while you remember to follow up.',
  'search-intel': 'Use as your AI-era SEO health check — the queries people now ask ChatGPT and Perplexity are not the same as Google, and you must rank in both.',
  'geo-audit': 'Best for international brands — AI engines answer the same prompt very differently per country, and only an audit reveals where you are invisible.',
  'seo-auditor': 'Use on every important landing page — most SEO mistakes are mechanical (missing tags, broken meta) and the auditor flags them all in one pass.',
  'seo-crawler': 'Best for sites with 100+ URLs — a full crawl finds the silent issues (orphan pages, broken redirects) you would never notice manually.',
  'seo-tasks': 'Use to turn audit findings into actual fixes — a kanban board keeps SEO work moving instead of dying in a forgotten spreadsheet.',
  'local-seo': 'Best for any business with a physical location — local pack rankings drive 70%+ of foot traffic, and listings drift out of date fast.',
  'web-vitals': 'Use whenever conversion or rankings drop unexplained — Core Web Vitals failures silently hurt both user experience and Google rankings.',
  'social-tags': 'Best to run before any major launch — broken Open Graph tags make every shared link on Facebook/LinkedIn look ugly and tank click-through.',
  'deliverability': 'Use the day you set up a new sending domain — without correct SPF/DKIM/DMARC every cold email lands in spam and your sender reputation collapses.',
  'seo-widget': 'Best for service businesses needing inbound leads — the embed gives prospects a useful audit and gives you their email address in return.',
  'unified-inbox': 'Use to stop messages slipping through the cracks — when 8 channels feed one inbox, response time drops and customer satisfaction goes up.',
  'alert-routing': 'Best for teams of 3+ — routing rules ensure the right person is paged for the right alert instead of everyone ignoring a noisy channel.',
  'digest': 'Use to stay informed without doom-scrolling tools — one morning email summarises everything that moved overnight in 60 seconds of reading.',
  'tiktok-downloader': 'Best for creative research and inspiration boards — save the videos you want to riff on without screen-recording them on your phone.',

  // ── Grow ─────────────────────────────────────────────────────────────────
  'goals': 'Use before any quarter starts — without explicit numeric goals every dashboard is just decoration, not decision support.',
  'kpi-tracker': 'Best for proving marketing ROI to finance — long-term trend lines tell a much more honest story than any single weekly snapshot.',
  'action-center': 'Use as your daily landing page in InfoGenie — one screen shows what is launching today and what is broken right now.',
  'autoseo': 'Best for content-led businesses with consistent publishing needs — automation removes the bottleneck that usually kills SEO programs after month three.',
  'contentscorer': 'Use on every page before publish — a single content score catches the SEO and readability issues that quietly suppress traffic for years.',
  'link-suggester': 'Best for sites with 100+ articles — strong internal linking is the single highest-leverage SEO tactic most teams completely ignore.',
  'cro-lab': 'Use to make every traffic dollar work harder — a 10% lift in conversion is mathematically equivalent to a 10% increase in your entire ad budget.',
  'ai-audit-suite': 'Best for diagnosing why AI engines do not cite you — these audits show specifically which entities, prompts and pages are missing.',
  'aivisibility': 'Use monthly — your share of AI answers is becoming as important as your share of Google rankings, and almost no team is measuring it yet.',
  'meta-insights': 'Best for catching Meta surprises early — the platform UI buries the metrics that actually matter; this surfaces them in a single chart.',
  'google-ads-insights': 'Use weekly to spot wasted spend — Google Ads quietly burns budget on broad-match terms unless someone is watching the search-terms report.',
  'tiktok-ads-insights': 'Best for brands testing TikTok seriously — without a clean view of ROAS by creative, you cannot tell which video format actually works for you.',
  'social-analytics': 'Use to find the channel mix worth investing in — if a platform is not growing reach AND engagement, it is not worth the team time.',
  'optimizer': 'Best for buyers managing 10+ campaigns — the optimiser does in 6 hours what would take a media buyer all week, while you sleep.',
  'analytics-hub': 'Use to merge SEO and product data in one place — landing-page conversion is what closes the loop between Search Console and GA4.',
  'amplitude-agents': 'Best for product-led growth teams — funnel insights surface drop-off points humans typically miss because the data is too granular to scan.',
  'blended-perf': 'Use for board-level reporting — blended CAC and ROAS are the only numbers a CEO or CFO actually cares about, not platform-by-platform stats.',
  'attribution': 'Best for shops running 4+ paid channels — multi-touch attribution finally answers the "which channel really drives revenue?" debate honestly.',
  'true-roas': 'Use when offline revenue matters — Meta and Google only see the ad-attributed portion; True ROAS includes the closed-deal data they cannot see.',
  'churn-scorer': 'Best for subscription and SaaS businesses — saving an at-risk customer in week one of the risk window is 5x cheaper than winning a new one.',

  // ── Manage ───────────────────────────────────────────────────────────────
  'master-calendar': 'Use to stop double-booking and content collisions — when every team works in the same calendar, last-minute conflicts disappear.',
  'launches': 'Best for product, marketing and PR coordination — a launch calendar makes sure ads, content and press all hit the same week instead of staggered.',
  'reengage': 'Use quarterly on dormant customers — winning back a churned customer is 4-6x cheaper than acquiring a brand-new one of equal value.',
  'automations': 'Best for connecting tools that do not natively talk — turn "I should remember to do X when Y happens" into a rule that just runs.',
  'stakeholders': 'Use to attach a real owner to every task — work without a named owner is the single biggest reason marketing tasks slip every cycle.',
  'meeting-notes': 'Best for sales teams running 10+ calls a week — a 30-second summary plus BANT scoring beats nobody reading your transcripts ever.',
  'results': 'Use as your audit trail — knowing exactly what InfoGenie did, when and what changed afterward is what builds trust in the platform.',
  'weekly-report': 'Best for accountability — a recurring auto-report Monday morning means stakeholders never have to ask "how are we doing?" again.',
  'cross-channel': 'Use monthly to rebalance budget — channels almost never deserve equal funding, and side-by-side comparison surfaces the obvious shifts.',
  'csuite': 'Best for monthly leadership reviews — each role lens shows the metrics that exec actually cares about, not a generic everything-dashboard.',
  'white-label': 'Use if you are an agency — branded reports are what justify your retainer, not raw screenshots from somebody else\'s tool.',
  'bulk-reports': 'Best for agencies managing 10+ clients — generating reports one at a time is the fastest way to lose a Friday afternoon.',
  'agency': 'Use to keep client work properly separated — multi-tenant isolation prevents the embarrassing "wrong client\'s data" moment.',
  'technical-suite': 'Best for sites that have grown organically over years — technical debt accumulates silently and the full sweep is the only way to catch it all.',
  'workspaces': 'Use whenever multiple brands or clients live under one account — workspaces stop their data, audiences and campaigns from contaminating each other.',
  'settings': 'Best to revisit quarterly — connected integrations break, tokens expire, and a quiet integration is missed insight you are paying for.',
};
