'use strict';
const express=require('express');const db=require('../../db');const tenantCtx=require('../tenants/context');
const {createRateLimiter}=require('../security/rate_limit');const review=require('./google_ads_reconciliation_human_review');const router=express.Router();
const limiter=createRateLimiter({name:'google-ads-reconciliation-review',windowMs:60_000,max:60,failClosed:true,keyFn:(req)=>req&&req.user&&req.tenant?`${req.tenant.id}|${req.user.id}`:null});
function isHuman(req){return !!(req&&req.user&&Number.isSafeInteger(req.user.id)&&req.user.id>0&&req.viaApiKey!==true&&req.user.viaApiKey!==true&&req.session&&Number(req.session.userId)===req.user.id);}
function hasGrant(req){return !!(req&&req.tenant&&req.tenantRole&&Array.isArray(req.tenantRole.permissions)&&req.tenantRole.permissions.includes(review.PERMISSION));}
function status(code){return code==='human_session_required'||code==='authentication_required'?401:code==='permission_denied'?403:code==='review_case_not_found'||code==='reconciliation_not_found'?404:['version_conflict','idempotency_conflict','concurrent_creation_conflict'].includes(code)?409:400;}
function route(label,fn){return async(req,res)=>{try{if(!isHuman(req))return res.status(401).json({ok:false,error:'human_session_required'});if(!hasGrant(req))return res.status(403).json({ok:false,error:'permission_denied'});const tenantId=await tenantCtx.resolveTenantId(req,{label:`google-ads-reconciliation-review:${label}`});const common={tenantId,actorUserId:req.user.id,actorType:'human',hasPermission:(key)=>key===review.PERMISSION&&hasGrant(req)};return res.json({ok:true,...await fn(common,req)});}catch(e){return res.status(status(e.code)).json({ok:false,error:e.code||'review_request_failed'});}};}
router.post('/',limiter,express.json(),route('create',async(o,req)=>({case:await review.createOrGet(db.getPool(),{...o,reconciliationRunId:req.body&&req.body.reconciliation_run_id})})));
router.get('/',limiter,route('list',async(o,req)=>review.listCases(db.getPool(),{...o,state:req.query.state,limit:req.query.limit,cursor:req.query.cursor})));
router.get('/:caseId',limiter,route('get',async(o,req)=>({case:await review.getCase(db.getPool(),{...o,caseId:req.params.caseId})})));
for(const [action,method] of [['acknowledge','acknowledge'],['escalate','escalate'],['close','close']])router.post(`/:caseId/${action}`,limiter,express.json(),route(action,async(o,req)=>({case:await review[method](db.getPool(),{...o,caseId:req.params.caseId,decisionId:req.body&&req.body.decision_id,expectedVersion:req.body&&req.body.expected_version,classification:req.body&&req.body.classification,note:req.body&&req.body.note})})));
module.exports=router;module.exports._isHuman=isHuman;module.exports._hasGrant=hasGrant;module.exports._limiter=limiter;
