'use strict';
const express=require('express'),db=require('../../db'),tenantCtx=require('../tenants/context'),{createRateLimiter}=require('../security/rate_limit'),service=require('./optimization_execution_run'),router=express.Router();
function human(req){const p=String(req?.user?.principalType||req?.user?.principal_type||'').toLowerCase();return !!(req?.user&&Number.isSafeInteger(req.user.id)&&req.user.id>0&&p==='human'&&req.viaApiKey!==true&&req.user.viaApiKey!==true&&req.session&&Number(req.session.userId)===req.user.id&&req.sessionID);}
const grant=req=>!!req?.tenantRole?.permissions?.includes(service.PERMISSION),limiter=createRateLimiter({name:'optimization-execution-runs',windowMs:60_000,max:20,failClosed:true,keyFn:req=>human(req)&&req.tenant?`${req.tenant.id}|${req.user.id}`:null}),fail=code=>{throw Object.assign(new Error(code),{code});};
function exact(v,allowed,required=allowed){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k))||required.some(k=>!Object.hasOwn(v,k)))fail('validation_failed');}
function status(c){return c==='human_session_required'?401:c==='permission_denied'?403:['request_not_found','execution_not_found'].includes(c)?404:['source_ineligible','already_executed','invocation_id_conflict','version_conflict','invalid_transition','execution_disabled','settlement_conflict','settlement_indeterminate'].includes(c)?409:400;}
function identify(req,res,next){if(!human(req))return res.status(401).json({error:'human_session_required'});next();}
function route(label,fn){return async(req,res)=>{try{if(!human(req))fail('human_session_required');if(!grant(req))fail('permission_denied');const tenantId=await tenantCtx.resolveTenantId(req,{label:`optimization-execution-runs:${label}`}),common={pool:db.getPool(),tenantId,actorUserId:req.user.id,actorType:'human',principalType:'human',sessionId:req.sessionID,hasExplicitTenantPermission:k=>k===service.PERMISSION&&grant(req)};res.json(await fn(common,req));}catch(e){res.status(status(e.code)).json({error:e.code||'optimization_execution_run_failed'});}};}
const json=express.json({limit:'2kb'});
router.post('/:requestId/execute',identify,limiter,json,route('execute',(o,r)=>{exact(r.body,['invocation_id']);return service.execute({...o,requestId:r.params.requestId,invocationId:r.body.invocation_id});}));
router.get('/:executionId',identify,limiter,route('get',(o,r)=>{if(Object.keys(r.query).length)fail('validation_failed');return service.get({...o,executionId:r.params.executionId});}));
router.get('/',identify,limiter,route('list',(o,r)=>{if(Object.keys(r.query).some(k=>!['limit','cursor','state'].includes(k)))fail('validation_failed');return service.list({...o,...r.query});}));
router.post('/:executionId/cancel',identify,limiter,json,route('cancel',(o,r)=>{exact(r.body,['expected_version']);return service.cancel({...o,executionId:r.params.executionId,expectedVersion:r.body.expected_version});}));
module.exports=router;module.exports._human=human;module.exports._grant=grant;module.exports._limiter=limiter;
